### PR TITLE
#4922 Fix: attachment missing after switch to forward

### LINKED ISSUE #4922: switch to forward is missing files
1) click encrypted reply to a particular email
2) switch reply to forward using the dropdown on top right
3) I'm forwarding now but it's missing the attachments from previous email

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed attachment missing issue after switch to forward 

close #4922 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/chrome/elements/compose-modules/compose-render-module.ts [hunk 1]
```diff
@@ -220,7 +220,7 @@ export class ComposeRenderModule extends ViewModule<ComposeView> {
     }
     this.view.recipientsModule.clearRecipients();
     if (option === 'a_forward') {
-      await this.view.quoteModule.addTripleDotQuoteExpandFooterAndQuoteBtn(this.view.replyMsgId, 'forward');
+      await this.view.quoteModule.addTripleDotQuoteExpandFooterAndQuoteBtn(this.view.replyMsgId, 'forward', true);
```
Comment (sosnovsky) [inline extension/chrome/elements/compose-modules/compose-render-module.ts:223]: I think we should force reload compose box when switching to reply too, as currently when you click `Secure Forward` and then switch to `Secure Reply` message includes attachment, but we doesn't need it for reply.

You can also set `forceReload` to true only when message includes attachment, because we need reload there only for attachments update.

Comment (ioanmo226) [reply extension/chrome/elements/compose-modules/compose-render-module.ts:223]: OK

Comment (ioanmo226) [reply extension/chrome/elements/compose-modules/compose-render-module.ts:224]: Please check new change

Comment (sosnovsky) [reply extension/chrome/elements/compose-modules/compose-render-module.ts:224]: Works well now 👍

File: test/source/tests/compose.ts [hunk 2]
```diff
@@ -1684,6 +1684,22 @@ export const defineComposeTests = (testVariant: TestVariant, testWithBrowser: Te
...
+        const appendUrl = 'threadId=18625ff9e8642033&skipClickPrompt=___cu_false___&replyMsgId=18625ff9e8642033';
+        const composePage = await ComposePageRecipe.openStandalone(t, browser, 'compatibility', {
+          appendUrl,
+          hasReplyPrompt: true,
+        });
+        await composePage.waitAndClick('@encrypted-reply');
+        await composePage.waitAndClick('@action-show-reply-options-popover');
+        await composePage.waitAndClick('@action-toggle-a_forward');
+        // Check attachment is still present after switch to forward
+        await composePage.waitForContent('.qq-upload-file', 'test.txt');
```
Comment (sosnovsky) [inline test/source/tests/compose.ts:1699]: Let's also add testing switch back to reply here, to test that attachments are removed.

**Review by sosnovsky — APPROVED** [review]
👍
