### PR TITLE
#4792 fix: compose issue when account not connected

### LINKED ISSUE #4792: Account reconnection pops-up when sending a password-protected messages
Users cannot send a password-protected message as the account reconnection pops up every time the send button was clicked.

Steps to reproduce:
1. Compose a pw-protected message
2. Send the pw-protected message
3. Account reconnection message will pop up -- try to reconnect the account the refresh the webpage
4. repeat step 1 & 2 and the account reconnection message will appear again preventing the user from sending the pw-message.

Screenshot:
image

Reference: 
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZfCdPtdKFTbMWkkrtqctmJB
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZgLpSTPjSWsdNBfkVNbFBkC
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZjcnFHfBwGNKvMgznTbDbzh
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThfFwlRtBWnPxjgwGtNnD
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZjcdjsFWLMXvsktCbbWfkTq
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTqwFLQmngvRvzmQSJDtTr
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTqrhnNlNPxsrQLgzPrpss
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTqpQgpGPTHLwvKkBRQkDw
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThfGjjvFmZQKFMLdSLcQc
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThXXwcSkGkbHSfKDWPTlc
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTFVbFHqVgFZrgfkDxQHQZ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTNqpLZqSpNWkJtkfrsXWQ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTXDKgtnmwBxFxmVRVJsGZ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTXHjJGvfgJVrcrNMSkXNs
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTXJpSpspRWgKhPnxblgkC
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZgLVZXWzjSGxZVWCXmRTMxJ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThQmNLnBBfjGBMxcRdVzq
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThRsPgHFpLpMbjWXgHrpm
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThVKgMksXVPkBJbPFStMV
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThcwGLWpVbMhgrZBJDvSJ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThWQhfthVjwgglQfWVCJG

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed compose issue when account not connected

close #4792 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by rrrooommmaaa** [comment]
Hi @ioanmo226 
How exactly was it fixed?
Do we need the account to be connected to send a PWD-protected message? in both FES and Flowcrypt API setups?
Is the message actually sent after the pop-up is approved? Do we expect it to?

File: extension/js/common/settings.ts [hunk 1]
```diff
@@ -380,7 +381,7 @@ export class Settings {
       await Ui.modal.info(`Reload after logging in.`);
       return window.location.reload();
     }
-    const authRes = await GoogleAuth.newOpenidAuthPopup({ acctEmail });
+    const authRes = await BrowserMsg.send.bg.await.reconnectAcctAuthPopup({ acctEmail });
```
Comment (ioanmo226) [inline extension/js/common/settings.ts:384]: Before when calling `GoogleAuth.newOpenidAuthPopup` directly, extension couldn't handle auth window because it's running via content script.
To fix that, we have to send event to background page.

Comment (ioanmo226) [reply extension/js/common/settings.ts:384]: Before, when user taps `OK` button, it indeed shows google auth popup. But couldn't handle result after that.
image

**Review by rrrooommmaaa — APPROVED** [review]

File: extension/js/common/settings.ts (hunk 1 above)
Comment (ioanmo226) [reply extension/js/common/settings.ts:384]: Got it. Thank you for adding additional check
