### PR TITLE
#5133 Fix broken email threading for draft messages

### LINKED ISSUE #5133: Broken threading after replying from Firefox
Bug needs investigation:
1) I received message from `User 1` addressed to me and another recipient `User 2`
2) I wrote reply and sent it with `reply-all`
3) Reply message is rendered in the same thread for me, but for `User 1` and `User 2` it created new thread
4) Next replies are rendered in the same thread, so only first one caused creating new thread

It's not clear why it happened, can be missing `msgId` or something else, so needs finding way to reproduce this bug.

### PR DESCRIPTION
**Pull request by martgil**
This PR fixes the broken email threading for FlowCrypt's secure draft messages.

close #5133 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/js/content_scripts/webmail/gmail/gmail-element-replacer.ts [hunk 1]
```diff
@@ -589,8 +589,10 @@ export class GmailElementReplacer extends WebmailElementReplacer {
     return from ? Str.parseEmail(from) : undefined;
   };
 
-  private getLastMsgReplyParams = (convoRootEl: JQuery): FactoryReplyParams => {
-    return { replyMsgId: this.determineMsgId($(convoRootEl).find(this.sel.msgInner).last()) };
```
Comment (martgil) [inline extension/js/content_scripts/webmail/gmail/gmail-element-replacer.ts:593]: This change goes to correct the logic of the existing code. Since the last container of the message to obtain the msgId does not mean to be where the container where the secure compose get's clicked.

What I mean by is, assume there are several existing converstations in an email thread (doesn't matter if its a group message). Assume the user clicks secure reply for a specific email that is placed in the middle order of the converstation, this will access the appropriate container rather than the last container of the conversation of the opened email thread.

**Review by sosnovsky — COMMENTED** [review]
Works correct now, great job on finding bug origin 👏

File: extension/js/content_scripts/webmail/gmail/gmail-element-replacer.ts (hunk 1 above)
Comment (martgil) [reply extension/js/content_scripts/webmail/gmail/gmail-element-replacer.ts]: I understand clearly now. Thanks for reviewing this PR.

**Comment by martgil** [comment]
Hello again @sosnovsky - thanks for reviewing this PR. This is now good to go.

**Comment by martgil** [comment]
Request to review and merge https://github.com/FlowCrypt/flowcrypt-browser/pull/5870 first when possible.

**Comment by martgil** [comment]
Hello again @sosnovsky - The other PR may experience too many failed tests. In that case, I think we can now merge this one. thanks!

File: extension/chrome/elements/compose-modules/compose-render-module.ts [hunk 2]
```diff
@@ -98,9 +98,11 @@ export class ComposeRenderModule extends ViewModule<ComposeView> {
       const thread = await this.view.emailProvider.threadGet(this.view.threadId, 'metadata');
       const inReplyToMessage = thread.messages?.find(message => message.id === this.view.replyMsgId);
       if (inReplyToMessage) {
-        this.view.replyParams.inReplyTo = inReplyToMessage.payload?.headers?.find(
-          header => header.name === 'Message-Id' || header.name === 'Message-ID'
-        )?.value;
+        const msgId = inReplyToMessage.payload?.headers?.find(header => header.name === 'Message-Id' || header.name === 'Message-ID')?.value;
+        if (msgId) {
+          this.view.sendBtnModule.additionalMsgHeaders['In-Reply-To'] = msgId;
+          this.view.sendBtnModule.additionalMsgHeaders.References = msgId;
```
Comment (sosnovsky) [inline extension/chrome/elements/compose-modules/compose-render-module.ts:104]: `references` header should include value of previous msg + `msgId`, like at https://github.com/FlowCrypt/flowcrypt-browser/blob/aa27485fa1229beeb255b426d6ec9ef20c807b73/extension/chrome/elements/compose-modules/compose-render-module.ts#L121

Comment (martgil) [reply extension/chrome/elements/compose-modules/compose-render-module.ts:104]: Thanks, I've fixed this as well.

**Comment by martgil** [comment]
@sosnovsky This is now good to go. Thanks!

File: extension/chrome/elements/compose-modules/compose-render-module.ts [hunk 3]
```diff
@@ -98,9 +98,12 @@ export class ComposeRenderModule extends ViewModule<ComposeView> {
...
       if (inReplyToMessage) {
-        this.view.replyParams.inReplyTo = inReplyToMessage.payload?.headers?.find(
-          header => header.name === 'Message-Id' || header.name === 'Message-ID'
-        )?.value;
+        const msgId = inReplyToMessage.payload?.headers?.find(header => header.name === 'Message-Id' || header.name === 'Message-ID')?.value;
+        const references = inReplyToMessage.payload?.headers?.find(header => header.name === 'References')?.value;
+        if (msgId && references) {
+          this.view.sendBtnModule.additionalMsgHeaders['In-Reply-To'] = msgId;
+          this.view.sendBtnModule.additionalMsgHeaders.References = references + ' ' + msgId;
+        }
```
[the remark this answers is not in the document]
Comment (martgil) [reply extension/chrome/elements/compose-modules/compose-render-module.ts]: I didn't know about this. I've reconsidered it made a few corrections.

**Comment by martgil** [comment]
Hello @sosnovsky, I've added a few improvements, including the fix for the requested change. Thanks!

**Comment by martgil** [comment]
Hello @sosnovsky, I've added a few improvements, including the fix for the requested change. Thanks!

File: extension/chrome/elements/compose-modules/compose-render-module.ts [hunk 4]
```diff
@@ -98,9 +98,11 @@ export class ComposeRenderModule extends ViewModule<ComposeView> {
...
       const inReplyToMessage = thread.messages?.find(message => message.id === this.view.replyMsgId);
       if (inReplyToMessage) {
-        this.view.replyParams.inReplyTo = inReplyToMessage.payload?.headers?.find(
-          header => header.name === 'Message-Id' || header.name === 'Message-ID'
-        )?.value;
+        const msgId = inReplyToMessage.payload?.headers?.find(header => header.name === 'Message-Id' || header.name === 'Message-ID')?.value;
+        const references = inReplyToMessage.payload?.headers?.find(header => header.name === 'References')?.value;
+        if (msgId && references) {
+          this.setReplyHeaders(msgId, references);
+        }
```
Comment (sosnovsky) [inline extension/chrome/elements/compose-modules/compose-render-module.ts:105]: no need to check `if (msgId && references)`, as they both are optional parameters for `setReplyHeaders`, and we have check for `if (msgId)` inside `setReplyHeaders`

Comment (martgil) [reply extension/chrome/elements/compose-modules/compose-render-module.ts]: got it, I've removed the unneeded checks.

**Review by sosnovsky — APPROVED** [review]
All good now, thanks!

**Comment by martgil** [comment]
Thanks Roma for reviewing this.
