### PR TITLE
#4710 fix: updated test/welcome endpoint

### LINKED ISSUE #4710: change test/welcome to welcome-message
Also `attester/test/welcome` should become `attester/welcome-message` and it should include `Bearer id_token` auth header (not enforced yet but will eventually enforce)

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/issues/1984#issuecomment-1255197555_

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR changed `test/welcome` endpoint to `welcome-message`.

close #4710 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/chrome/settings/setup.ts [hunk 1]
```diff
@@ -318,7 +320,8 @@ export class SetupView extends View {
     }
     const pub = await KeyUtil.parse(armoredPubkey);
     if (pub.usableForEncryption) {
-      this.pubLookup.attester.testWelcome(this.acctEmail, armoredPubkey).catch(ApiErr.reportIfSignificant);
+      const idToken = await InMemoryStore.get(this.acctEmail, InMemoryStoreKeys.ID_TOKEN);
+      this.pubLookup.attester.testWelcome(this.acctEmail, armoredPubkey, idToken).catch(ApiErr.reportIfSignificant);
```
Comment (tomholub) [inline extension/chrome/settings/setup.ts:324]: Also the method may be called `welcomeMessage`

File: extension/js/common/api/key-server/attester.ts [hunk 2]
```diff
@@ -103,12 +103,13 @@ export class Attester extends Api {
     return r.responseText;
   };
```
Comment (tomholub) [inline extension/js/common/api/key-server/attester.ts:104]: Sorry to hijack this PR but I think this `updatePubkey` is probably not used? If it's not used, please remove the method. If used, please replace usage with either `submitPrimaryEmailPubkey` or `submitPubkeyWithConditionalEmailVerification`

Comment (ioanmo226) [reply extension/js/common/api/key-server/attester.ts:104]: It's used here. 
But problem is this method passes `longId` instead of `email`. 
`submitPrimaryEmailPubkey` and `submitPubkeyWithConditionalEmailVerification` method doesn't seem to accept longId

https://github.com/FlowCrypt/flowcrypt-browser/blob/2baf09ee3bec3d7bcfae0a93c547f03be7548cff/extension/chrome/settings/modules/my_key_update.ts#L79

Comment (tomholub) [reply extension/js/common/api/key-server/attester.ts]: Ah. Looks good.

**Review by tomholub — APPROVED** [review]
