### PR TITLE
#5340 Check if attachment is decrypted before downloading

### LINKED ISSUE #5340: Fix error when downloading attachment from PGP/MIME message
When trying to download attachment from PGP/MIME message there is an error message shown:

> There was a problem decrypting this file (format: Error: Error during parsing. This message / key probably does not conform to a valid OpenPGP format.). Downloading encrypted original.

But attachment is downloaded decrypted. It happens because extension thinks that attachment is encrypted, and tries to decrypt it again.

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR adds check if attachment is decrypted before trying to download it, to fix error message which appeared when extension tried to decrypt already decrypted attachment.

close #5340

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/chrome/elements/pgp_block_modules/pgp-block-attachments-module.ts [hunk 1]
```diff
@@ -82,6 +82,16 @@ export class PgpBlockViewAttachmentsModule {
     BrowserMsg.send.showAttachmentPreview(this.view.parentTabId, { iframeUrl });
   };
 
+  private downloadAttachment = async (attachment: Attachment) => {
```
Comment (tomholub) [inline extension/chrome/elements/pgp_block_modules/pgp-block-attachments-module.ts:85]: Let's call it `decryptIfNeededAndDownloadAttachment`

**Review by tomholub — APPROVED** [review]
