### PR TITLE
Ensure msgBody has dummy parent after being replaced

### LINKED ISSUE #2271: Cannot read property 'replaceChild' of null"
### Step to reproduce:

1. Open any encrypted message from Inbox
2. Click the remove Inbox label button:
image
After clicking the remove label button, this error is in console: `Error in protected function: Cannot read property 'replaceChild' of null"`
3. Click the "Undo" button in the bottom toast notification:
image

### Expected behavior

Nothing happens

### Actual behavior

The encrypted message is being re-rendered:

### PR DESCRIPTION
**Pull request by limonte**
Closes #2271

### CODE REVIEW

File: extension/js/content_scripts/webmail/gmail-element-replacer.ts [hunk 1]
```diff
@@ -468,6 +470,13 @@ export class GmailElementReplacer implements WebmailElementReplacer {
     }
   }
 
+  private ensureHasParentNode = (el: JQuery<HTMLElement>) => {
```
Comment (limonte) [inline extension/js/content_scripts/webmail/gmail-element-replacer.ts]: @tomholub because it's a common DOM helper, should it be moved somewhere else from here?

**Comment by limonte** [comment]
@tomholub what do you think about this solution?

File: extension/js/content_scripts/webmail/gmail-element-replacer.ts (hunk 1 above)
Comment (tomholub) [reply extension/js/content_scripts/webmail/gmail-element-replacer.ts]: I can only imagine ever needing it in Gmail webmail, so I think it's placed correctly.

**Comment by tomholub** [comment]
Code style tests are failing due to suspected xss. In this case it's not a concert, so you can comment it with `dummyParent.append(el); // xss-direct`

**Comment by limonte** [comment]
> Code style tests are failing due to suspected xss. In this case it's not a concert, so you can comment it with `dummyParent.append(el); // xss-direct`

Done :+1:
