### PR TITLE
Fixed extractPubkeys

### LINKED ISSUE #3659: Export all contacts feature broken
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGkXSTdrbjTDpCcDmDRkPpnBsfh

>I found one bug about the export contact. I click export all contact but seem like file size is 0 byte.

I tried this myself and the same happens. I click `FlowCrypt Settings -> Additional Settings -> Contacts -> export all`, it downloads a file, I open it, aannnd, empty!

When we patch this, we should also add a test to prevent this from popping up again in the future.

If anyone knows something obvious that's causing this let me know, otherwise just feel free to assign this to me and I'll start debugging it.

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
This PR fixes `ContactStore.extractPubkeys()`

close #3659

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: test/source/tests/browser-unit-tests/unit-ContactStore.js [hunk 1]
```diff
@@ -531,3 +531,31 @@ BROWSER_UNIT_TEST_NAME(`ContactStore doesn't replace revoked key with older vers
...
+    email: 'abcdef@test.com', pubkey: testConstants.abcdefTestComPubkey
+  });
+  const contactABCDDF = await ContactStore.obj({
+    email: 'abcddf@test.com', pubkey: testConstants.abcddfTestComPubkey
+  });
+  const contactABDDEF = await ContactStore.obj({
+    email: 'abddef@test.com', pubkey: testConstants.abddefTestComPubkey
+  });
+  await ContactStore.save(db, [contactABBDEF, contactABCDEF, contactABCDDF, contactABDDEF]);
+  const foundKeys = await ContactStore.searchPubkeys(db, { hasPgp: true });
```
Comment (rrrooommmaaa) [inline test/source/tests/browser-unit-tests/unit-ContactStore.js:551]: Actually, we can shortcut the `ContactStore.searchPubkeys(db, { hasPgp: true })` to simply load all keys from `pubkeys` store instead of using `search` index on emails. There are no other calls on `searchPubkeys` in the project as of now.

Comment (tomholub) [reply test/source/tests/browser-unit-tests/unit-ContactStore.js:551]: Understood, ok to do

**Review by tomholub — APPROVED** [review]
Good for this particular PR, but it would be good to test this with UI tests (click the export all button, and expect pubkeys to come out).
