### PR TITLE
#5904 fix: persist reply mode when switching to secure compose 

### LINKED ISSUE #5904: Persist reply mode when switching to secure forward
When switching to `secure forward` using this red banner, it switches to `secure reply` but should persist `forward` mode:

steps to reproduce:
- open thread with encrypted message
- click `...` button in top right corner of encrypted message
- click `Forward` in the message menu
- compose box appears with red banner
- click `Switch to encrypted compose`
- it switches to `secure reply`, but should be `secure forward`

In 8.5.6 release it worked correctly, probably caused by some changes in our latest release.
Also need to add test for this case, to avoid similar issues in the next releases.

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed persist reply mode issue when switching to secure compose

close #5904// if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/js/content_scripts/webmail/gmail/gmail-element-replacer.ts [hunk 1]
```diff
@@ -640,7 +640,6 @@ export class GmailElementReplacer extends WebmailElementReplacer {
     const legacyDraftReplyRegex = new RegExp(/\[(flowcrypt|cryptup):link:draft_reply:([0-9a-fr\-]+)]/);
     const newReplyBoxes = $('div.nr.tMHS5d, td.amr > div.nr, div.gA td.I5').not('.reply_message_evaluated').filter(':visible').get();
     if (newReplyBoxes.length) {
-      this.replyOption = undefined;
```
Comment (sosnovsky) [inline extension/js/content_scripts/webmail/gmail/gmail-element-replacer.ts:643]: removing this line caused unexpected draft creation bug reappear - https://github.com/FlowCrypt/flowcrypt-browser/issues/5616#issuecomment-1972897692

Comment (ioanmo226) [reply extension/js/content_scripts/webmail/gmail/gmail-element-replacer.ts:643]: Ohhh, Yep
I now remember, Thank you for that notice.

Comment (sosnovsky) [reply extension/js/content_scripts/webmail/gmail/gmail-element-replacer.ts:643]: let's add comment about this issue above this line, so we won't miss it in the future.

**Review by sosnovsky — APPROVED** [review]
Works great now, thanks!
