### PR TITLE
#5020 Fix: cc and bcc ui issue

### LINKED ISSUE #5020: CC and BCC UI issue
Please look at the following screenshots

image
image

Cursor in the web extension is located opposite BCC. it's confusing. When I was creating a message I thought I used BCC.

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed cc and bcc ui issue

close #5020 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/chrome/elements/compose-modules/compose-recipients-module.ts [hunk 1]
```diff
@@ -1253,6 +1277,14 @@ export class ComposeRecipientsModule extends ViewModule<ComposeView> {
     }
   };
 
+  private setCorrectPaddingForInputContainer = () => {
+    if (this.addedRecipients.some(r => r.sendingType === 'cc')) {
+      $('#input-container-cc').css('padding-bottom', this.inputContainerPaddingBottom);
+    } else if (this.addedRecipients.some(r => r.sendingType === 'to')) {
+      $('#input-container-to').css('padding-bottom', this.inputContainerPaddingBottom);
+    }
```
Comment (sosnovsky) [inline extension/chrome/elements/compose-modules/compose-recipients-module.ts:1285]: here code is almost the same for both cases, what about simplifying it to

```ts
for (const sendingType of ['to', 'cc']) {
      if (this.addedRecipients.some(r => r.sendingType === sendingType)) {
        $(`#input-container-${sendingType}`).css('padding-bottom', this.inputContainerPaddingBottom);
      }
    }
```

**Review by sosnovsky — COMMENTED** [review]
Works well, but I noticed a minor issue:
- enter `to`, `cc` and `bcc` recipients
- switch to message text input
- switch back to recipients input
- in this PR an empty non-clickable space is added after `cc` recipient

`master`:
Screenshot 2025-02-11 at 12 55 44

this PR:
Screenshot 2025-02-11 at 12 54 08

File: extension/chrome/elements/compose-modules/compose-recipients-module.ts (hunk 1 above)
Comment (ioanmo226) [reply extension/chrome/elements/compose-modules/compose-recipients-module.ts:1285]: Sounds good 👍

File: extension/chrome/elements/compose-modules/compose-recipients-module.ts [hunk 2]
```diff
@@ -914,6 +919,20 @@ export class ComposeRecipientsModule extends ViewModule<ComposeView> {
...
+        if ($('#input-container-cc').css('display') === 'none' && $('#input-container-bcc').css('display') === 'none') {
+          container.parent().css('padding-bottom', this.inputContainerPaddingBottom);
+        }
+      }
+      if (sendingType === 'cc') {
+        if ($('#input-container-bcc').css('display') === 'none') {
+          container.parent().css('padding-bottom', this.inputContainerPaddingBottom);
+        }
+      }
+    }
```
[the remark this answers is not in the document]
Comment (ioanmo226) [reply extension/chrome/elements/compose-modules/compose-recipients-module.ts:934]: Yep!

**Review by sosnovsky — APPROVED** [review]
works well now 👍
