### PR TITLE
issue 2590 key manager integration

### LINKED ISSUE #1500: better logging of 500 errors
The stack trace below is not very useful. Exactly what did the err 500 say? That would be useful.

```
Error: Internal Server Error: 500 when POST-ing https://flowcrypt.com/api/message/upload object:
at Function.Api.ajax (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/api.js:599:11)

provided ajax call stack:
at Object.apiCall (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/api.js:679:42)
at Object.apiFcCall (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/api.js:690:56)
at Object.messageUpload (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/api.js:501:31)
at Composer.doEncryptFmtSend (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/composer.js:722:49)
at <async> ajax (/extension/js/common/api/api.ts:670:23)
at <async> apiCall (/extension/js/common/api/api.ts:723:13)
at <async> messageUpload (/extension/js/common/api/api.ts:583:19)
at <async> doEncryptFmtSend (/extension/js/common/composer.ts:788:29)
at <async> encryptSend (/extension/js/common/composer.ts:633:24)

url: ...
```

### LINKED ISSUE #2590: FlowCrypt Email Key Manager integration
1) org rule `private_key_manager_url`
2) org rule flag `PRV_AUTOIMPORT_OR_AUTOGEN` and `PASS_PHRASE_QUIET_AUTOGEN`

### PR DESCRIPTION
**Pull request by tomholub**
close #2590
close #1500

- [x] add rules
- [x] create tests
- [x] hide `Add Key`
- [x] add code to enforce key algo during generating (also during regular keygen)
- [x] test km not available only after keygen
- [x] hide pp settings
- [x] test KS not reachable + add specialized err

### CODE REVIEW

File: extension/chrome/settings/setup/setup-key-manager-autogen.ts [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+import { Ui } from '../../../js/common/browser/ui.js';
+import { Url } from '../../../js/common/core/common.js';
+import { AcctStore } from '../../../js/common/platform/store/acct-store.js';
+import { Buf } from '../../../js/common/core/buf.js';
+import { PgpPwd } from '../../../js/common/core/pgp-password.js';
+import { ApiErr } from '../../../js/common/api/error/api-error.js';
+import { Api } from '../../../js/common/api/api.js';
+import { Settings } from '../../../js/common/settings.js';
+
+export class SetupKeyManagerAutogenModule {
```
Comment (tomholub) [inline extension/chrome/settings/setup/setup-key-manager-autogen.ts]: Todo - give this a final read

File: extension/chrome/settings/setup/setup-render.ts [hunk 2]
```diff
@@ -28,13 +28,15 @@ export class SetupRenderModule {
...
-        return await Settings.promptToRetry('REQUIRED', e, Lang.setup.failedToLoadEmailAliases, () => this.renderInitial());
+        return await Settings.promptToRetry(e, Lang.setup.failedToLoadEmailAliases, () => this.renderInitial());
       }
       $('.auth_denied_warning').toggleClass('hidden', this.view.scopes!.read || this.view.scopes!.modify);
     }
     if (this.view.storage!.setup_done) {
       if (this.view.action !== 'add_key') {
         await this.renderSetupDone();
+      } else if (this.view.rules.mustAutoImportOrAutogenPrvWithKeyManager()) {
+        // todo - handle autogen case
```
Comment (tomholub) [inline extension/chrome/settings/setup/setup-render.ts]: todo - evaluate this
