### PR TITLE
#4541 Fix: any in ci_unit_test

### LINKED ISSUE #4541: fix forge definitions usage to not use any
Also this is wrong to add forge into squire definitions. Let's remove it and file an issue for Ioan to have a look later.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/4508#discussion_r920921712_

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed any in ci_unit_test

close #4541 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
FYI, I also think it's safe to use `any` in window variable declaration(like Tom mentioned) and we should use `as any` for this line as we can't know which lib we are going to define.

`(window as any)[(lib as any).name] = lib`

https://github.com/FlowCrypt/flowcrypt-browser/issues/4541#issuecomment-1184192647

File: extension/chrome/dev/ci_unit_test.ts [hunk 1]
```diff
@@ -38,9 +38,10 @@ const libs: unknown[] = [
   Catch,
   Gmail,
 ];
-
+/* eslint-disable @typescript-eslint/no-explicit-any */
```
Comment (rrrooommmaaa) [inline extension/chrome/dev/ci_unit_test.ts:41]: Do you think it may be worth trying to go this direction (adding properties to `Window` interface)?
https://stackoverflow.com/a/12709880

Comment (ioanmo226) [reply extension/chrome/dev/ci_unit_test.ts:41]: yeah, it's worth it.
But for this line, we can't implement like that.

> (window as any)[(lib as any).name] = lib

Comment (ioanmo226) [reply extension/chrome/dev/ci_unit_test.ts:41]: I think (window as any) is enough for this logic

**Review by rrrooommmaaa — APPROVED** [review]
