### PR TITLE
#4496 fix: switch to encrypted reply

### LINKED ISSUE #4496: "switch to encrypted reply" no longer works
image

To reproduce, in my case:
 - receive several encrypted messages in a thread
 - pick the one in the middle
 - click "reply all" using standard gmail interface
 - then see above banner
 - clicking `Switch to encrypted reply` doesn't work

Actually, the reason this happened is because I didn't see any "encrypted reply" option on the message itself. It seems that it's missing on encrypted messages that have many recipients:

image

but it's present and functioning on encrypted messages with just me as a recipient:

image

So that needs to be addressed as well.

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixes switch to encrypted reply issue for messages (Thread messages which is not the last message)

close #4496 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: test/source/tests/gmail.ts [hunk 1]
```diff
@@ -24,10 +24,21 @@ export type GmailCategory = 'inbox' | 'sent' | 'drafts' | 'spam' | 'trash';
...
+      t: AvaContext,
+      browser: BrowserHandle,
+      gmailPage: ControllablePage,
+      {
+        isReplyPromptAccepted,
+        composeCount
+      }:
+      {
+        isReplyPromptAccepted?: boolean,
+        composeCount?: number
```
Comment (rrrooommmaaa) [inline test/source/tests/gmail.ts:37]: I suggest a more precise name: `composeFrameCount`

File: test/source/tests/gmail.ts [hunk 2]
```diff
@@ -296,6 +307,19 @@ export const defineGmailTests = (testVariant: TestVariant, testWithBrowser: Test
       await gmailPage.notPresent('.reply_message_evaluated .error_notification'); // should not show the warning about switching to encrypted reply
     }));
 
+    ava.default('mail.google.com - switch to encrypted reply for middle message', testWithBrowser('ci.tests.gmail', async (t, browser) => {
+      const gmailPage = await openGmailPage(t, browser);
+      await gotoGmailPage(gmailPage, '/FMfcgzGqRGfPBbNLWvfPvDbxnHBwkdGf'); // plain convo
```
Comment (rrrooommmaaa) [inline test/source/tests/gmail.ts:312]: About a year ago we started to put test messages from the live account to the `test/source/mock/google/live-gmail-test-emails` folder in plain EML format to be able to restore the message in case it's accidentally deleted from the server. It's appropriate to have the id from the test `FMfcgzGqRGfPBbNLWvfPvDbxnHBwkdGf` in the file name.
Of course, need to take care that the message doesn't contain any sensitive data (such as email addresses of people who wouldn't want to disclose their email addresses).

**Review by rrrooommmaaa — CHANGES_REQUESTED** [review]
The implementation looking good.
There are a few things we can update in tests, please see comments.

File: test/source/tests/gmail.ts [hunk 3]
```diff
@@ -24,10 +24,21 @@ export type GmailCategory = 'inbox' | 'sent' | 'drafts' | 'spam' | 'trash';
...
+      {
+        isReplyPromptAccepted?: boolean,
+        composeCount?: number
+      } = {}
+    ) => {
       const urls = await gmailPage.getFramesUrls(['/chrome/elements/compose.htm'], { sleep: 0 });
-      expect(urls.length).to.equal(1);
+      expect(urls.length).to.equal(composeCount ?? 1);
       if (typeof isReplyPromptAccepted !== 'undefined') {
         const replyBox = await browser.newPage(t, urls[0]);
```
[the remark this answers is not in the document]
Comment (ioanmo226) [reply test/source/tests/gmail.ts:43]: To be frank, I also agree with you.
I think original author's thought was like this.
Will follow your way.

> Is this because in our particular test the "secure reply compose container" is located higher than the other "reply or forward buttons" container

**Review by rrrooommmaaa — APPROVED** [review]
