### PR TITLE
issue 2689 WellKnownHostMeta integration and tests

### LINKED ISSUE #2689: prepwork for FlowCrypt Enterprise Server integration
Today, stack traces are sent to FlowCrypt API - done in `Cather.report` and `Catcher.handleErr`. There should be a way to send them to a configured FES instance.

### PR DESCRIPTION
**Pull request by tomholub**
issue #2689 - still not integrated into codebase, just improvements and unit tests

 - [ ] update FES docs in https://github.com/FlowCrypt/enterprise-server/issues/16
 - [x] unit test - fetches it but no url set
 - [x] unit test - fetches it with fes url set
 - [x] unit test - not json
 - [x] unit test - wrong format
 - [x] unit test - 404
 - [x] unit test - 500
 - [x] unit test - grabs from cache, fetches it successfully, then grabs from cache
 - [x] unit test - grabs from cache, fetches it with zero result, then grabs from cache

### CODE REVIEW

File: extension/js/common/api/api.ts [hunk 1]
```diff
@@ -56,7 +56,7 @@ export class Api {
       };
       request.onerror = errHandler;
       request.ontimeout = errHandler;
-      request.onload = e => resolve(new Buf(request.response as ArrayBuffer));
+      request.onload = e => request.status <= 299 ? resolve(new Buf(request.response as ArrayBuffer)) : errHandler(e);
```
Comment (tomholub) [inline extension/js/common/api/api.ts:59]: It used to resolve even on err500 responses, unit tests uncovered this

**Review by tomholub — COMMENTED** [review]
lgtm
