### PR TITLE
#5032 Show clearer error message why key is not usable

### LINKED ISSUE #5032: clearer error message as to why key is not usable
User is getting `This OpenPGP key is not usable.` which doesn't say much, but we do seem to have access to the actual problem as visible from compatibility test:

> **(14) PK 0 > Encrypt/Decrypt test: Got error performing encryption/decryption test: Error: Error encrypting message: Could not find valid encryption key packet in key 87e87b1cf73b7e44: elgamal keys are considered too weak.:**

The error message could  be clearer, so we could say eg `Could not find valid encryption key packet in key 87e87b1cf73b7e44: elgamal keys are considered too weak.` instead of `This OpenPGP key is not usable.` when importing (or wherever that error was originally encountered.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/5030#issuecomment-1479323251_

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR implemented fix to show clearer error message why key is not usable

close #5032 // if this PR closes an issue

image

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/chrome/elements/pgp_pubkey.ts [hunk 1]
```diff
@@ -167,8 +184,9 @@ View.run(
       }
     };
 
-    private showKeyNotUsableError = () => {
+    private showKeyNotUsableError = async () => {
       $('.error_container').removeClass('hidden');
+      $('.error_introduce_label').text(`This OpenPGP key is not usable.\n${await this.getErrorText()}`);
```
Comment (sosnovsky) [inline extension/chrome/elements/pgp_pubkey.ts:189]: let's use `<small>` html tag for error description, it will take less space than normal text size.
also `error: error encrypting message:` part can't be removed, so error message will begin directly from error reason:


and incorrect key row is misaligned with other rows, probably because of smaller `view key` button. let's make it the same width as `import key` button.

Comment (ioanmo226) [reply extension/chrome/elements/pgp_pubkey.ts:189]: Sounds good!

**Review by sosnovsky — APPROVED** [review]
looks good now 👍
