### PR TITLE
#6115 Fix: Incorrect date issue when printing message

### LINKED ISSUE #6115: Incorrect date when printing message
Customer reported that in some cases message date is incorrect when using print function, as it displays date of the first message in the thread instead of the selected message date.

I was able to reproduce this issue:
- open thread with multiple encrypted messages
- click `expand all` button:

Image

- click `print` on the second message in the thread
- print page will use date of the first message, instead of the second

This bug isn't reproducible when first message isn't expanded - print page correctly uses date of the selected message in this case.
So seems like this bug in parsing message date happens when the first thread message is visible.

### PR DESCRIPTION
**Pull request by ioanatflowcrypt**
This PR fixed incorrect date issue when printing message

close #6115 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/js/common/message-renderer.ts [hunk 1]
```diff
@@ -461,10 +461,7 @@ export class MessageRenderer {
 
   private getMessageInfo = async (fullMsg: GmailRes.GmailMsg): Promise<MessageInfo> => {
     const sentDate = GmailParser.findHeader(fullMsg, 'date');
-    let sentDateStr = $('div.gK span[title]').attr('title');
-    if (!sentDateStr || isNaN(Date.parse(sentDateStr))) {
-      sentDateStr = sentDate ? new Date(sentDate).toLocaleString() : '';
-    }
+    const sentDateStr = sentDate ? new Date(sentDate).toLocaleString() : '';
```
Comment (sosnovsky) [inline extension/js/common/message-renderer.ts]: earlier we've used similar code, but got user feedback about incorrect format of date when printing messages, so we've switched to parsing message date directly from Gmail page (https://github.com/FlowCrypt/flowcrypt-browser/pull/5676)

so in this issue it'll be better to stick with webpage date parsing, but fix it to get correct message date

**Comment by ioanatflowcrypt** [comment]
@sosnovsky Seems like you need to enable auto-merge
