### PR TITLE
issue 2825 unsupported key type unknown

### LINKED ISSUE #2825: Error: Unsupported key type: unknown
```
Error: Unsupported key type: unknown
at Function.KeyUtil.parseMany (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/key.js:87:15)
at Function.KeyUtil.parse (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/crypto/key.js:71:31)
at KeyImportUi.read (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key-import-ui.js:205:41)
at KeyImportUi.checkPrv (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/ui/key-import-ui.js:113:46)
at async AddKeyView.addPrivateKeyHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/add_key.js:72:37)
at <async> parseMany (/extension/js/common/core/crypto/key.ts:142:28)
at <async> parse (/extension/js/common/core/crypto/key.ts:138:24)
at <async> read (/extension/js/common/ui/key-import-ui.ts:215:17)
at <async> checkPrv (/extension/js/common/ui/key-import-ui.ts:135:20)

### Catch.reportErr calling stack ###
# at Function.Catch.formattedStackBlock (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:302:44)
# at Function.Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:132:26)
# at AddKeyView.addPrivateKeyHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/add_key.js:87:31)
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/add_key.htm?placement=settings&parentTabId=740%3A0&acctEmail=...
#
######################
```

### PR DESCRIPTION
**Pull request by tomholub**
close #2825

### CODE REVIEW

File: extension/chrome/settings/modules/add_key.ts [hunk 1]
```diff
@@ -84,6 +84,8 @@ View.run(class AddKeyView extends View {
         return await Ui.modal.warning(e.message, Ui.testCompatibilityLink);
       } else if (e instanceof KeyCanBeFixed) {
         return await Ui.modal.error(`This type of key cannot be set as non-primary yet. Please write human@flowcrypt.com`, false, Ui.testCompatibilityLink);
+      } else if (e instanceof Error && e.message === 'Unsupported key type: unknown') {
+        return await Ui.modal.warning(`Pasted content does not appear to be a validly formatted OpenPGP key.\n\n(Unsupported key type: unknown)`);
```
Comment (wiktor-k) [inline extension/chrome/settings/modules/add_key.ts:88]: A question: should we rather introduce a new kind of Error that we could `instanceof` with?

> validly formatted OpenPGP key

No mention of S/MIME? Maybe `does not appear to be a validly formatted OpenPGP nor S/MIME key` ?

Comment (tomholub) [reply extension/chrome/settings/modules/add_key.ts:88]: > A question: should we rather introduce a new kind of Error that we could instanceof with?

sounds good, I'll do that

> No mention of S/MIME? Maybe does not appear to be a validly formatted OpenPGP nor S/MIME key ?

Here testing for private keys, that's why only OpenPGP.

However we have a customer very, very interested in importing their s/mime private keys too.

Comment (tomholub) [reply extension/chrome/settings/modules/add_key.ts:88]: But as far as parsing goes, you're right - it checks for pgp or s/mime. I thought it would be somewhat confusing if we said pgp or s/mime, and then if they proceeded to enter valid s/mime, we would error again because we don't actually support it.

But that should be super rare, and would actually be and interesting way to have users write us that they are interested in this, so I'll do that :)

Comment (wiktor-k) [reply extension/chrome/settings/modules/add_key.ts:88]: > However we have a customer very, very interested in importing their s/mime private keys too.
Good to hear! I imagine after adding private S/MIME keys this modal message could be easily overlooked later so why not fix it now :)
Thanks!
