### PR TITLE
#5922 Improve stability of gmail live tests

### LINKED ISSUE #5922: Improve stability of Gmail live tests
> @martgil live tests probably fail because of current 45 minutes execution limit - https://github.com/FlowCrypt/flowcrypt-browser/blob/cbc16870e7aa3765f79ff10c7c1c99e6d62849d3/.semaphore/semaphore.yml#L64
Let's increase it to 60 minutes for now, but later will try to merge some live tests, so they'll be executed faster.

_Originally posted by @sosnovsky in https://github.com/FlowCrypt/flowcrypt-browser/issues/5909#issuecomment-2632094823_

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR improved stability of gmail live tests

close #5922 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
Interesting....
After merging 3 tests into one, live test takes a bit longer than before.

image

**Comment by sosnovsky** [comment]
there are also several tests which we temporarily disabled because of their instability, they should be improved and re-enabled too:
- `saving and rendering compose drafts when offline`
- `secure reply btn, reply draft`
- `keep original reply message when switching to secure mode`
- `switch to encrypted forward`

File: test/source/tests/gmail.ts [hunk 1]
```diff
@@ -301,7 +320,9 @@ export const defineGmailTests = (testVariant: TestVariant, testWithBrowser: Test
     );
 
     // convo-sensitive, draft-sensitive test
-    // skipped temporarily as per https://github.com/FlowCrypt/flowcrypt-browser/issues/5934#issuecomment-2664926769, originally uses test.serial
+    // Couldn't figure out why pageHasSecureDraft can't find correct iframe
+    // Need to fix later
+    // https://flowcrypt.semaphoreci.com/jobs/0106da6d-46f5-44d3-9ebd-3421584220a0
     test.skip(
       'mail.google.com - secure reply btn, reply draft',
```
Comment (ioanmo226) [inline test/source/tests/gmail.ts:327]: @sosnovsky Tried to fix this test but couldn't figure out.
SemaphoreCI couldn't be able to find element in compose draft frame in `pageHasSecureDraft`.
Maybe leave it for future fix?
Or you have other why this happens?

**Review by sosnovsky — APPROVED** [review]
looks good 👍
