### PR TITLE
#4792 fix: Password protected message issue when FES is not used

### LINKED ISSUE #4792: Account reconnection pops-up when sending a password-protected messages
Users cannot send a password-protected message as the account reconnection pops up every time the send button was clicked.

Steps to reproduce:
1. Compose a pw-protected message
2. Send the pw-protected message
3. Account reconnection message will pop up -- try to reconnect the account the refresh the webpage
4. repeat step 1 & 2 and the account reconnection message will appear again preventing the user from sending the pw-message.

Screenshot:
image

Reference: 
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZfCdPtdKFTbMWkkrtqctmJB
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZgLpSTPjSWsdNBfkVNbFBkC
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZjcnFHfBwGNKvMgznTbDbzh
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThfFwlRtBWnPxjgwGtNnD
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZjcdjsFWLMXvsktCbbWfkTq
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTqwFLQmngvRvzmQSJDtTr
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTqrhnNlNPxsrQLgzPrpss
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTqpQgpGPTHLwvKkBRQkDw
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThfGjjvFmZQKFMLdSLcQc
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThXXwcSkGkbHSfKDWPTlc
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTFVbFHqVgFZrgfkDxQHQZ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTNqpLZqSpNWkJtkfrsXWQ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTXDKgtnmwBxFxmVRVJsGZ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTXHjJGvfgJVrcrNMSkXNs
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTXJpSpspRWgKhPnxblgkC
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZgLVZXWzjSGxZVWCXmRTMxJ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThQmNLnBBfjGBMxcRdVzq
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThRsPgHFpLpMbjWXgHrpm
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThVKgMksXVPkBJbPFStMV
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThcwGLWpVbMhgrZBJDvSJ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThWQhfthVjwgglQfWVCJG

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR password protected message send issue when FES is not used

close #4792 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
@martgil Please try if this branch fixed current password protected message issue or try after this branch is merged to master

**Comment by martgil** [comment]
I can try it before it gets merged. I'll let you know my feedback here in this PR shortly.

**Comment by martgil** [comment]
I tested it and it seemed the issue was fixed 👍

File: test/source/tests/gmail.ts [hunk 1]
```diff
@@ -126,6 +126,14 @@ export const defineGmailTests = (testVariant: TestVariant, testWithBrowser: Test
       expect(urls.length).to.eq(1);
     }));
 
+    ava.default('mail.google.com - send password protected message', testWithBrowser('ci.tests.gmail', async (t, browser) => {
```
Comment (rrrooommmaaa) [inline test/source/tests/gmail.ts:129]: The fix looks good, but why do we need a live test?
Is this because we don't check authorization in our '/api/message/upload'  handler in `backend-endpoints.ts`  (Flowcrypt API emulation)? We can try to add the extra checks there too, have you tried that? This way, I suppose, the previous compose test would suffice to cover the issue.

Comment (ioanmo226) [reply test/source/tests/gmail.ts]: You are right. 👍 
We indeed don't need live test for this.

File: test/source/mock/backend/backend-endpoints.ts [hunk 2]
```diff
@@ -53,4 +50,16 @@ const throwIfNotPost = (req: IncomingMessage) => {
   if (!isPost(req)) {
     throw new HttpClientErr('Backend mock calls must use POST method');
   }
+};
+
+const throwIfInvalidOrMissingIdToken = (req: IncomingMessage) => {
```
Comment (rrrooommmaaa) [inline test/source/mock/backend/backend-endpoints.ts:55]: Let's rename it to `getEmailFromIdTokenOrThrow` as `throwIf...` doesn't suppose a return value.

We can merge this, however, I noticed that the API endpoint of `/api/message/upload` is called twice successfully. We can discuss and analyze in a separate issue whether we can retain `UploadedMessageData` from the first successful call to re-use it in the subsequent sending.

Comment (ioanmo226) [reply test/source/mock/backend/backend-endpoints.ts:55]: What do you mean called twice? was this api called twice somewhere?
> I noticed that the API endpoint of /api/message/upload is called twice successfully.

**Review by tomholub — APPROVED** [review]

File: test/source/mock/backend/backend-endpoints.ts (hunk 2 above)
Comment (rrrooommmaaa) [reply test/source/mock/backend/backend-endpoints.ts]: > What do you mean called twice? was this api called twice somewhere?

Yes, in `compose - test compose after reconnect account` test, the endpoint `/api/message/upload` was accessed twice -- before account reconnection and after account reconnection, both times successfully (the authentication header was obviously valid) -- so as I understand the message was uploaded to the backend twice (I'm planning to re-check the FES upload too)

Comment (ioanmo226) [reply test/source/mock/backend/backend-endpoints.ts]: I checked but it's called twice because of below reason.
When it tries to send pwd-protected message first time(it calls upload api 1st time), it returns error because id_token is missing.
After that app asks user to re-authorize google extension and then re-tries to send message again. (this time it calls upload api 2nd time)

Comment (rrrooommmaaa) [reply test/source/mock/backend/backend-endpoints.ts]: > When it tries to send pwd-protected message first time(it calls upload api 1st time), it returns error because id_token is missing.

Sending a PWD-protected message message consists of 2 phases:
1) uploading the PWD-encrypted message to a flowcrypt/FES server, getting message link(s)
2) sending a message containing links/pubkey-encrypted message to `gmail`.
Which phase gives an error? In the mock environment, only the 2. Perhaps, it's worthwhile to update the mock environment/test to mimic the real situation more precisely.

Anyway, this isn't critical, just a consideration.
A possible scenario:
1) PWD-encrypted message gets successfully uploaded, we have `UploadedMessageData`
2) sending message(s) to `gmail` fails (for whatever reason), but auto-retried (e.g. after reconnecting the account)
3) If possible, PWD-encrypted message shouldn't be re-uploaded, provided the inputs are the same (the sender, the recipients, the text etc.) -- which is probably true for auto-resends.
4) sending message(s) to `gmail` using either previous `UploadedMessageData` or the previously built messages -- but the point of concern here is the situation when the user "reconnected" to another gmail account if that's possible.

Comment (ioanmo226) [reply test/source/mock/backend/backend-endpoints.ts]: I think 1st phase gives error in mock environment.
1st phase tries to upload PWD-encrypted message to FES using /message/upload url. (Mock environment returns error when id_token is missing or invalid)
Therefore, I think current logic is correct. 
> Which phase gives an error? In the mock environment, only the 2.

Comment (rrrooommmaaa) [reply test/source/mock/backend/backend-endpoints.ts]: What I saw during the test was:
1) The mock FES endpoint accepted the token as valid.
2) The mock Google endpoint rejected the token as invalid.
Is this a peculiarity of the test setup or a possible live situation? Please describe your thoughts on this.

Anyway, Google endpoint may possibly reject a message for reasons other than invalid token. The point of #4801 is when we have successfully uploaded the pwd-encrypted message in phase 1, we should retain the message tokens (returned by FES) by reasonably simple means, to re-use them in automatic google-message re-sends. Of course, these tokens should be invalidated if a recipient of the message is added (removed?) or the message text is changed.

So #4801 is worth considering without direct relation to the invalid token issue.

Comment (ioanmo226) [reply test/source/mock/backend/backend-endpoints.ts]: Hmm... I didn't experience this. So mock FES treats id_token as valid but mock google endpoint treats id_token as invalid?
Could you tell me reproduce steps?
> What I saw during the test was:

Comment (rrrooommmaaa) [reply test/source/mock/backend/backend-endpoints.ts]: > Could you tell me reproduce steps?

The test `compose - test compose after reconnect account`

Comment (ioanmo226) [reply test/source/mock/backend/backend-endpoints.ts]: 👍  let me check

Comment (rrrooommmaaa) [reply test/source/mock/backend/backend-endpoints.ts]: > So mock FES treats id_token as valid

Not FES, `backend` -- flowcrypt API. but this doesn't really matter

Comment (ioanmo226) [reply test/source/mock/backend/backend-endpoints.ts]: Just finished checking and I now fully understand your concern.
But if we want to change like above way, we need to change compose send infra and need to change several tens of lines of codes and might make code messy.
Moreover, I think it's fine to call /message/upload twice because id_token will change after google re-auth(or something like that) and backend might need to return different data than previous one.

Let me know your thought @rrrooommmaaa
