### PR TITLE
#5966 Add reliable checks for ambigious file extensions

### LINKED ISSUE #5966: Public key detection doesn't work reliably on certain public key attachment
There is this very specific public key attachment that doesn't invoke FlowCrypt automatic public key import prompt for quick import public key as attachments.

The email support below contains a .eml file from which it contains public key attachments that although has `application/pgp-keys` has this name: `abc.def@ghi.com.asc` (not their real email add).

https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzQZTzVdDXmCqkbJVqxxBNRtsQSM

The reporting user however had proceed to manually importing the public key which works just fine as the public key itself is valid and usable.

### PR DESCRIPTION
**Pull request by martgil**
This PR does fix .asc public key attachment not recognized.

Fix:

image

Current behavior: 

image

Closes #5966 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by martgil** [comment]
Hi @sosnovsky, this one is ready for a review. thanks!

File: extension/js/common/core/attachment.ts [hunk 1]
```diff
@@ -204,7 +204,7 @@ export class Attachment {
     } else if (this.name === 'message' && isBodyEmpty) {
       // treat message as encryptedMsg when empty body for the 'message' attachment
       return 'encryptedMsg';
-    } else if (this.name.match(/(\.pgp$)|(\.gpg$)|(\.[a-zA-Z0-9]{3,4}\.asc$)/g)) {
+    } else if (this.name.match(/(\.pgp$)|(\.gpg$)|(\.[a-zA-Z0-9]{3,4}\.asc$)/g) && !this.isPublicKey() && !this.isPrivateKey()) {
```
Comment (sosnovsky) [inline extension/js/common/core/attachment.ts:207]: what about adding test for this case? probably shouldn't be too complicated, but will help to not break this solution in the future

Comment (martgil) [reply extension/js/common/core/attachment.ts:207]: Thank you for the remarks. You're right, and I missed that opportunity as I initially thought it wouldn't need testing. I'll definitely need to add a test for this.

**Comment by martgil** [comment]
Hi again @sosnovsky, I've added a small test for this change. Do you think it will be sufficient?

**Review by sosnovsky — APPROVED** [review]
all good now, thanks!
