### PR TITLE
#4868 fix: correctly parse draft saved from iOS app and get rid of tags

### LINKED ISSUE #4868: Extension doesn't recognize draft saved from iOS app
When I created draft in iOS app and opened draft in browser extension, it doesn't show `Open Draft`(which will open secure compose view with decrypted content)

image

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR correctly parses draft saved from iOS app and get rid of tags

close #4868 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Couldn't add test (Need to add live test for parsing existing drafts. However, implementing a live test would present a stability issue as drafts cannot be exported and may be discarded prior to the start of the live test or whatsoever reason)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by sosnovsky** [comment]
@ioanmo226 I found a bug here:
1) compose 2 drafts
2) open first draft
3) open second draft - compose modal still shows data from the first draft

**Comment by ioanmo226** [comment]
Nice catch 👍 
Let me fix it.

**Comment by sosnovsky** [comment]
Found another issue:
1) try to open legacy encrypted draft with `flowcrypt:link...` prefix
2) flowcrypt extension asks for passphrase
3) don't enter pasphrase and click `Close`
4) reload page
5) try to open this draft again, enter your passphrase
6) draft text is empty

Such situation should be quite rare, but will lead to losing customer's drafts which can be a big issue.

Also sometimes original gmail box doesn't disappear and is shown along with FlowCrypt encrypted compose box, like this:

Screenshot 2023-01-18 at 16 22 43

**Comment by ioanmo226** [comment]
> @ioanmo226 I found a bug here:

this one is fixed.

**Comment by ioanmo226** [comment]
> found a bug here:

However, this but is also on master branch and I suggest to fix it in another PR/branch.
This fix might contain more changes than expected.

**Comment by ioanmo226** [comment]
FYI in this PR, I removed `Open Draft` button logic. (This extra step sounds bad to me)
Why do we need `Open Draft` button instead of replacing secure compose window directly?

File: extension/js/content_scripts/webmail/gmail-element-replacer.ts [hunk 1]
```diff
@@ -295,29 +295,34 @@ export class GmailElementReplacer implements WebmailElementReplacer {
...
+      // For thread reply draft, we don't need to call openComposeWin
+      // Reply draft window will be replaced by secure compose by replaceStandardReplyBox function
+      const isComposeDraft = $(contenteditable).closest('table.aoP').find('img.ajn').length < 1;
+      if (PgpArmor.isEncryptedMsg(draftHtml) && isComposeDraft) {
+        draftId = String($(contenteditable).closest('.I5').find('input[name="draft"]')?.val())?.split(':')[1] ?? '';
+      }
+      if (draftId) {
         // close original draft window
-        const closeGmailComposeWindow = (target: HTMLElement) => {
+        const closeGmailComposeWindow = (target: HTMLElement | JQuery<HTMLElement>) => {
```
Comment (sosnovsky) [inline extension/js/content_scripts/webmail/gmail-element-replacer.ts:318]: We can use just `JQuery<HTMLElement>` here, as plain `HTMLElement` won't be passed anymore.

File: extension/js/content_scripts/webmail/gmail-element-replacer.ts [hunk 2]
```diff
@@ -295,29 +295,34 @@ export class GmailElementReplacer implements WebmailElementReplacer {
...
           const mouseUpEvent = document.createEvent('Event');
           mouseUpEvent.initEvent('mouseup', true, true); // Gmail listens for the mouseup event, not click
-          $(target).closest('.dw').find('.Ha')[0].dispatchEvent(mouseUpEvent); // jquery's trigger('mouseup') doesn't work for some reason
+          $(target).closest('.nH.Hd').find('.Ha')[0].dispatchEvent(mouseUpEvent); // jquery's trigger('mouseup') doesn't work for some reason
```
Comment (sosnovsky) [inline extension/js/content_scripts/webmail/gmail-element-replacer.ts:321]: After changing `target` type to `JQuery<HTMLElement>`, this can be changed to `target.closest('.nH.Hd')...`

File: extension/js/content_scripts/webmail/gmail-element-replacer.ts (hunk 1 above)
Comment (ioanmo226) [reply extension/js/content_scripts/webmail/gmail-element-replacer.ts:318]: Sounds good :+1

File: extension/chrome/elements/compose-modules/compose-draft-module.ts [hunk 3]
```diff
@@ -215,22 +213,6 @@ export class ComposeDraftModule extends ViewModule<ComposeView> {
...
-      // new message compose draft with known draftId
-      prefix = `[flowcrypt:link:draft_compose:${this.view.draftId}]\n\n`;
-    } else {
-      prefix = `(saving of this draft was interrupted - to decrypt it, send it to yourself)\n\n`;
-    }
-    if (sendable.body['text/plain']) {
-      sendable.body['text/plain'] = `${prefix}${sendable.body['text/plain'] || ''}`;
-    }
-  };
-
```
[the remark this answers is not in the document]
Comment (ioanmo226) [reply extension/chrome/elements/compose-modules/compose-draft-module.ts]: Maybe you are right.
Let me revert this part.

**Comment by sosnovsky** [comment]
> However, this bug is also on master branch and I suggest to fix it in another PR/branch. This fix might contain more changes than expected. What do you think @sosnovsky

Yes, that's okay, can be fixed in another PR

**Review by sosnovsky — APPROVED** [review]
👍
