### PR TITLE
#5295 Return undefined when emailProvider.msgGet's raw is undefined

### LINKED ISSUE #5295: Cannot read properties of undefined (reading 'replace')
> title: TypeError                                         message: Cannot read properties of undefined (reading 'replace')                                         url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?isReplyBox=___cu_tru                                         line: 213                                         column: 40                                         environment: chrome:ex:prod                                         build type: consumer

```
TypeError: Cannot read properties of undefined (reading 'replace')
at Buf.fromBase64UrlStr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/core/buf.js:213:40)
at ComposeQuoteModule.getAndDecryptMessage (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-quote-module.js:88:59)
at async ComposeQuoteModule.addTripleDotQuoteExpandFooterAndQuoteBtn (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-quote-module.js:43:56)
at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-render-module.js:97:29

### Catch.reportErr calling stack ###
# at Catch.formatExceptionForReport (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:273:90)
# at Catch.onErrorInternalHandler (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:81:29)
# at Catch.reportErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/platform/catch.js:97:18)
# at ComposeQuoteModule.getAndDecryptMessage (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-quote-module.js:173:31)
# at async ComposeQuoteModule.addTripleDotQuoteExpandFooterAndQuoteBtn (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-quote-module.js:43:56)
# at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-render-module.js:97:29
#
# url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?isReplyBox=___cu_true___&frameId=frame_fEzlJcPTER&skipClickPrompt=___cu_true___&ignoreDraft=___cu_false___&replyMsgId=%23msg-a%3Ar-764059238457043807&acctEmail=[SCRUBBED]&parentTabId=227631385%3A0
#
######################
```

### PR DESCRIPTION
**Pull request by martgil**
This PR fixes the issue when emailProvider.msgGet's raw is undefined.

close #5295 

Manually tested*

screenshot:

image

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/chrome/elements/compose-modules/compose-quote-module.ts [hunk 1]
```diff
@@ -88,8 +88,7 @@ export class ComposeQuoteModule extends ViewModule<ComposeView> {
     try {
       const { raw } = await this.view.emailProvider.msgGet(msgId, 'raw', progress => this.setQuoteLoaderProgress(progress));
       this.setQuoteLoaderProgress('processing...');
-      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
-      const decoded = await Mime.decode(Buf.fromBase64UrlStr(raw!));
+      const decoded = await Mime.decode(Buf.fromBase64UrlStr(raw || ''));
```
Comment (rrrooommmaaa) [inline extension/chrome/elements/compose-modules/compose-quote-module.ts:91]: calling `Mime.decode` on an empty string? To get an empty structure?
and then call `Mime.processDecoded` on the empty structure?
Wouldn't it be better to simply `return undefined` -- the function return type is `Promise<MessageToReplyOrForward | undefined>`?

**Review by rrrooommmaaa — CHANGES_REQUESTED** [review]

File: extension/chrome/elements/compose-modules/compose-quote-module.ts (hunk 1 above)
Comment (martgil) [reply extension/chrome/elements/compose-modules/compose-quote-module.ts]: That is right. I have added a check the value of `raw` and `return undefined` if it is indeed `undefined`. thank you. I learned from this.

**Review by rrrooommmaaa — APPROVED** [review]

File: extension/chrome/elements/compose-modules/compose-quote-module.ts [hunk 2]
```diff
@@ -88,7 +88,9 @@ export class ComposeQuoteModule extends ViewModule<ComposeView> {
     try {
       const { raw } = await this.view.emailProvider.msgGet(msgId, 'raw', progress => this.setQuoteLoaderProgress(progress));
       this.setQuoteLoaderProgress('processing...');
-      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
+      if (typeof raw === 'undefined') {
+        return undefined;
+      }
```
Comment (rrrooommmaaa) [inline extension/chrome/elements/compose-modules/compose-quote-module.ts:93]: you should remove `!` from `raw!` below on line 94

**Review by rrrooommmaaa — CHANGES_REQUESTED** [review]

File: extension/chrome/elements/compose-modules/compose-quote-module.ts [hunk 3]
```diff
@@ -88,7 +88,9 @@ export class ComposeQuoteModule extends ViewModule<ComposeView> {
...
       const decoded = await Mime.decode(Buf.fromBase64UrlStr(raw!));
```
Comment (sosnovsky) [inline extension/chrome/elements/compose-modules/compose-quote-module.ts:94]: after adding this check we can remove `!`:
`Buf.fromBase64UrlStr(raw!)` -> `Buf.fromBase64UrlStr(raw)`

File: extension/chrome/elements/compose-modules/compose-quote-module.ts (hunk 2 above)
Comment (martgil) [reply extension/chrome/elements/compose-modules/compose-quote-module.ts:93]: updated. thanks!

File: extension/chrome/elements/compose-modules/compose-quote-module.ts (hunk 3 above)
Comment (martgil) [reply extension/chrome/elements/compose-modules/compose-quote-module.ts]: updated. thanks!

File: extension/chrome/elements/compose-modules/compose-quote-module.ts [hunk 4]
```diff
@@ -88,8 +88,10 @@ export class ComposeQuoteModule extends ViewModule<ComposeView> {
     try {
       const { raw } = await this.view.emailProvider.msgGet(msgId, 'raw', progress => this.setQuoteLoaderProgress(progress));
       this.setQuoteLoaderProgress('processing...');
-      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
-      const decoded = await Mime.decode(Buf.fromBase64UrlStr(raw!));
+      if (typeof raw === 'undefined') {
+        return undefined;
+      }
```
Comment (ioanmo226) [inline extension/chrome/elements/compose-modules/compose-quote-module.ts:93]: Maybe we can simplify like below? This will check if raw is empty/null/undefined too though.
```ts
if (!raw) {
  return;
}
```

Comment (martgil) [reply extension/chrome/elements/compose-modules/compose-quote-module.ts]: Thanks, Ioan, for the remarks. I will apply the suggested code simplification.

Comment (ioanmo226) [reply extension/chrome/elements/compose-modules/compose-quote-module.ts]: Your welcome. You actually don't need `return undefined` too. `return` would be sufficient

**Review by sosnovsky — APPROVED** [review]
👍

**Comment by sosnovsky** [comment]
@rrrooommmaaa can you please approve this PR? As merging is blocked with your changes request

**Review by rrrooommmaaa — APPROVED** [review]
