### PR TITLE
issue 1599 stack passing fix

### LINKED ISSUE #1599: improve stack trace passing + aggregation
It's hard to follow the thread of events with incomplete stack traces.

A good way to produce sample useless stack trace:
```diff
  public static gmailCall = async (acctEmail: string, method: ReqMethod, path: string, params: Dict<Serializable> | string | undefined, progress?: ProgressCbs, contentType?: string) => {
    progress = progress || {};
    let data, url;
    if (typeof progress.upload === 'function') {
      url = 'https://www.googleapis.com/upload/gmail/v1/users/me/' + path + '?uploadType=multipart';
      data = params;
    } else {
      url = 'https://www.googleapis.com/gmail/v1/users/me/' + path;
      if (method === 'GET' || method === 'DELETE') {
        data = params;
      } else {
        data = JSON.stringify(params);
      }
    }
    contentType = contentType || 'application/json; charset=UTF-8';
    const headers = { 'Authorization': await GoogleAuth.googleApiAuthHeader(acctEmail) };
-   const xhr = Api.getAjaxProgressXhrFactory(progress);
+   const xhr = () => new XMLHttpRequest();
    const request = { xhr, url, method, data, headers, crossDomain: true, contentType, async: true };
    return await GoogleAuth.apiGoogleCallRetryAuthErrorOneTime(acctEmail, request);
  }
```

Then open https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#label/compatibility%2FGpgOL/WhctKHTCGjFCdWqLhrdswHHkHLlvfzTxXGNlZLsCqkMPhZWNfHDBtpDlDmPBgMfjbMwwsSb

Will produce, on Firefox:
```
[BrowserMsg.sendAwait(ajax) failed with lastError: The object could not be cloned.]
BrowserMsg.sendAwait@moz-extension://feb74b72-561a-4474-a9d3-8ffafde0330a/js/content_scripts/webmail_bundle.js:7978:68
ajax@moz-extension://feb74b72-561a-4474-a9d3-8ffafde0330a/js/content_scripts/webmail_bundle.js:7948:27
Api.ajax@moz-extension://feb74b72-561a-4474-a9d3-8ffafde0330a/js/content_scripts/webmail_bundle.js:5417:26
GoogleAuth.apiGoogleCallRetryAuthErrorOneTime@moz-extension://feb74b72-561a-4474-a9d3-8ffafde0330a/js/content_scripts/webmail_bundle.js:6237:26
Google.gmailCall@moz-extension://feb74b72-561a-4474-a9d3-8ffafde0330a/js/content_scripts/webmail_bundle.js:5666:22


url: https://mail.google.com/mail/u/0/#label/compatibility%2FGpgOL/WhctKHTCGjFCdWqLhrdswHHkHLlvfzTxXGNlZLsCqkMPhZWNfHDBtpDlDmPBgMfjbMwwsSb


processRawMsgResponse@moz-extension://feb74b72-561a-4474-a9d3-8ffafde0330a/js/content_scripts/webmail_bundle.js:7997:29

    at <async> ajax (/extension/js/common/api/api.ts:713:23)
    at <async> apiGoogleCallRetryAuthErrorOneTime (/extension/js/common/api/google.ts:548:53)
    at <async> gmailCall (/extension/js/common/api/google.ts:46:28)
```
That's a horribly useless stack trace, because it's not clear which api call caused this, or where.

Firefox console seems to drop a little more telling error:
```
Invalid object webmail_bundle.js:82:5
    onErrorInternalHandler moz-extension://feb74b72-561a-4474-a9d3-8ffafde0330a/js/content_scripts/webmail_bundle.js:82
    handleErr moz-extension://feb74b72-561a-4474-a9d3-8ffafde0330a/js/content_scripts/webmail_bundle.js:153
    replaceAtts moz-extension://feb74b72-561a-4474-a9d3-8ffafde0330a/js/content_scripts/webmail_bundle.js:9104
```
Which is better, at least we know it comes from `replaceAtts`.

But it fails to mention that the whole thing is caused by:
```js
const msg = await Google.gmail.msgGet(this.acctEmail, msgId, 'full');
```
Thus, stack traces should be improved at least to produce the right method name / position at least for this case.

I will see if a fix is possible at TypeScript compiler level, similar to how we do async stack traces. This would be preferable.

### PR DESCRIPTION
**Pull request by tomholub**
close #1599 

This is extremely interesting. For our particular codebase, and our (edited compiler), if we want the longest possible stack trace, we need to await promises explicitly instead of returning them.

bad:
```js
  threadGet = (threadId: string, format?: GmailResponseFormat, progressCb?: ProgressCb): Promise<GmailRes.GmailThread> => {
    return Google.gmailCall(this.acctEmail, 'GET', `threads/${threadId}`, { format }, { download: progressCb }) as GmailRes.GmailThread;
  }
```
good:
```js
  threadGet = async (threadId: string, format?: GmailResponseFormat, progressCb?: ProgressCb): Promise<GmailRes.GmailThread> => {
    return await Google.gmailCall(this.acctEmail, 'GET', `threads/${threadId}`, { format }, { download: progressCb }) as GmailRes.GmailThread;
  }
```
This is because we hacked the transpiler to insert a bunch of try/catch for stack traces, and they only get triggered when we actually await the promises before returning:

```js
this.threadGet = async (threadId, format, progressCb) => {
	try {
		return await Google.gmailCall(this.acctEmail, 'GET', `threads/${threadId}`, { format }, { download: progressCb });
	}
	catch (t) {
		if(t instanceof Error){t.stack+="\n    at <async> threadGet (/extension/js/common/api/email_provider/gmail/gmail.ts:39:14)";throw t}const e=new Error("Thrown["+typeof t+"]"+t);e.thrown=t;throw e;
	}
};
```
Without that added await, the catch clause would never get triggered, and we lose our beautiful async stack.

### CODE REVIEW

File: extension/js/common/api/api.ts [hunk 1]
```diff
@@ -33,14 +33,15 @@ export type ProgressCb = (percent?: number, loaded?: number, total?: number) =>
...
-  public static download = (url: string, progress?: ProgressCb): Promise<Buf> => {
-    return new Promise((resolve, reject) => {
-      const request = new XMLHttpRequest();
-      request.open('GET', url, true);
-      request.responseType = 'arraybuffer';
-      if (typeof progress === 'function') {
-        request.onprogress = (evt) => progress(evt.lengthComputable ? Math.floor((evt.loaded / evt.total) * 100) : undefined, evt.loaded, evt.total);
-      }
+
+  public static download = async (url: string, progress?: ProgressCb): Promise<Buf> => {
```
Comment (tomholub) [inline extension/js/common/api/api.ts]: Could be problematic, if runs at next tick

File: extension/js/common/api/backend.ts [hunk 2]
```diff
@@ -196,36 +196,36 @@ export class Backend extends Api {
...
+    return await Api.ajax({ url: 'https://flowcrypt.com/feed', dataType: 'json' }, Catch.stackTrace()) as BackendRes.FcBlogPost[]; // tslint:disable-line:no-direct-ajax
   }
 
-  public static s3Upload = (items: AwsS3UploadItem[], progressCb: ProgressCb) => {
+  public static s3Upload = async (items: AwsS3UploadItem[], progressCb: ProgressCb) => {
     const progress = Value.arr.zeroes(items.length);
     const promises: Promise<void>[] = [];
     if (!items.length) {
-      return Promise.resolve(promises);
+      return await Promise.resolve([]);
```
Comment (tomholub) [inline extension/js/common/api/backend.ts]: This no longer makes sense, just return empty array

File: extension/js/common/api/email_provider/gmail/gmail.ts [hunk 3]
```diff
@@ -316,7 +314,7 @@ export class Gmail extends EmailProviderApi implements EmailProviderInterface {
   }
 
   fetchAcctAliases = async (): Promise<GmailRes.GmailAliases> => {
-    return Google.gmailCall(this.acctEmail, 'GET', 'settings/sendAs', {});
+    return await Google.gmailCall(this.acctEmail, 'GET', 'settings/sendAs', {}) as GmailRes.GmailAliases;
```
Comment (tomholub) [inline extension/js/common/api/email_provider/gmail/gmail.ts]: can use <T>

File: extension/js/common/platform/store.ts [hunk 4]
```diff
@@ -651,97 +651,89 @@ export class Store {
...
-      if (!db) { // relay op through background process
-        // todo - currently will silently swallow errors
-        BrowserMsg.send.bg.await.db({ f: 'dbContactSave', args: [contact] }).then(resolve).catch(Catch.reportErr);
+  static dbContactSave = async (db: IDBDatabase | undefined, contact: Contact | Contact[]): Promise<void> => {
+    if (!db) { // relay op through background process
+      return await BrowserMsg.send.bg.await.db({ f: 'dbContactSave', args: [contact] }) as void;
+    }
+    return await new Promise((resolve, reject) => {
+      if (Array.isArray(contact)) {
+        Promise.all(contact.map(oneContact => Store.dbContactSave(db, oneContact))).then(() => resolve(), reject);
```
Comment (tomholub) [inline extension/js/common/platform/store.ts]: Could be moved above

File: tooling/tslint-rules/awaitReturnedPromiseRule.ts [hunk 5]
```diff
@@ -0,0 +1,48 @@
+import * as ts from "typescript";
+import * as tslint from "tslint";
+import { isIdentifier } from 'tsutils';
+
+const AWAIT_RETURNED_PROMISE = `must explicitly await returned promise (see https://github.com/FlowCrypt/flowcrypt-browser/pull/2349)`;
+
+export class Rule extends tslint.Rules.TypedRule {
```
Comment (tomholub) [inline tooling/tslint-rules/awaitReturnedPromiseRule.ts]: I tried to write this as ESLINT rule but failed. So it will have to be a tslint rule, at least for now.

**Comment by tomholub** [comment]
take a look at dbContactSearch / why undefined

```js
      } else {
        // todo - this seems to make no sense. No callback? Why undefined?
        // adding a reject below will break tests
        // reject(new Error('search is undefined in dbContactSearch'));
      }
```
