### PR TITLE
issue #3992 [Setup] Fix showing error modal when uploading invalid private key

### LINKED ISSUE #3992: Nothing happens when selecting an invalid key file during setting up the FlowCrypt Extension
### Steps to reproduce

1. Go To Settings -> Additional Settings -> Add key
2. Chose "Load from a file" option
3. Select this file [111.txt](https://github.com/FlowCrypt/flowcrypt-browser/files/7202566/111.txt)

### Alternative steps to reproduce

1. Start setting up the FlowCrypt extension for a new account or after resetting the existed one
2. Click "Enter existing key" button
2. Chose "Load from a file" option
3. Select this file [111.txt](https://github.com/FlowCrypt/flowcrypt-browser/files/7202566/111.txt)

### Actual behavior

Nothing happens, console is clear

### Expected behavior

Users should get feedback from their actions (e.g. the warning modal), if the selected file is invalid there should be an error message and optional error description.

### PR DESCRIPTION
**Pull request by limonte**
This PR fixes showing the error modal when user imports invalid key file. The functionality was already there, but it was broken.

close #3992

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: test/source/tests/page-recipe/settings-page-recipe.ts [hunk 1]
```diff
@@ -14,6 +14,7 @@ import { KeyUtil } from '../../core/crypto/key';
 export type SavePassphraseChecks = {
   isSavePassphraseHidden?: boolean | undefined,
   isSavePassphraseChecked?: boolean | undefined
+  isInvalidKey?: boolean | undefined
```
Comment (rrrooommmaaa) [inline test/source/tests/page-recipe/settings-page-recipe.ts:17]: This check isn't related to "save passphrase", so the type name `SavePassphraseChecks` would no longer be relevant.
Moreover, these checks are supposed to be optional (can be skipped), which is not the case with invalid key -- we HAVE to dismiss the alert to proceed with the recipe, so conceptually this is not the best place for this parameter.
Can we put it somewhere to `ManualEnterOpts` maybe?

**Review by rrrooommmaaa — APPROVED** [review]
