### PR TITLE
Get rid of #cryptup_dialog

### LINKED ISSUE #3677: #cryptup_dialog should close itself by Esc
Currently `#cryptup_dialog` doesn't close itself when user press `Esc`. Instead it allows `Esc` to propagate, which create the unexpected behavior, e.g. closing the "Secure Compose" window while `#cryptup_dialog` stays opened.

### Steps to reproduce

1. Start wiring the password-protected message
2. Click the "Add their public key" link
3. Press `Esc`

### Actual behavior

`#cryptup_dialog` stays opened while the "Secure Compose" window is getting closed.

### Expected behavior

`#cryptup_dialog` is getting closed while the "Secure Compose" window stays opened (stop event propagation).

### PR DESCRIPTION
**Pull request by limonte**
This PR removes a few instances of `#cryptup_dialog` usage and replaces them with already existed functionality of showing `<iframe>` inside SweetAlert2 modal.

close #3677

---

Also fixed the `.action_finish_session` button. It was unusable when a user has a long list of emails (the button was covered by email rows, their `z-index` is `2`):

CleanShot 2021-05-24 at 22 39 43

---

Also fixed the vertical alignment in `.button`, e.g. in `decrypt.htm`:

Before | After
-|-
CleanShot 2021-05-26 at 13 26 59@2x | CleanShot 2021-05-26 at 13 28 38@2x

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by limonte** [comment]
@tomholub ready for review. Hopefully I didn't break anything. I manually checked everything that could be related to replacing `#cryptup_dialog` with SweetAlert2.

**Comment by limonte** [comment]
Rebased onto the `master` branch so the tests will pass after fixing #3678

BTW @tomholub I changed the style of the "End Pass Phrase Session" button to be less transparent and full-width. While less transparent is certainly better:

CleanShot 2021-05-26 at 11 58 18@2x

the full-width is opinionated, let me know if you like it or not. If not, I'll revert the width.

image

**Comment by tomholub** [comment]
Less transparent is good and z-index is good, but I wonder if full-width wastes too much space?

**Comment by limonte** [comment]
> Less transparent is good and z-index is good, but I wonder if full-width wastes too much space?

I actually agree here. It's easy to forget that a lot of users have 1366×768 screen resolution and it is important not to waste any vertical space. Reverted full-width.

File: extension/js/common/xss-safe-factory.ts [hunk 1]
```diff
@@ -167,12 +176,15 @@ export class XssSafeFactory {
     return `<link class="${this.destroyableCls}" rel="stylesheet" href="${this.extUrl(`css/${file}.css`)}" />`;
   }
 
-  public dialogPassphrase = (longids: string[], type: PassphraseDialogType) => {
-    return this.divDialog_DANGEROUS(this.iframe(this.srcPassphraseDialog(longids, type), ['medium'], { scrolling: 'no' }), 'dialog-passphrase'); // xss-safe-factory
+  public showPassphraseDialog = async (longids: string[], type: PassphraseDialogType, initiatorFrameId?: string) => {
+    const result = await Ui.modal.iframe(this.srcPassphraseDialog(longids, type, initiatorFrameId), 500, 'dialog-passphrase');
+    if (result.dismiss === Swal.DismissReason.backdrop || result.dismiss === Swal.DismissReason.esc) {
```
Comment (rrrooommmaaa) [inline extension/js/common/xss-safe-factory.ts:181]: If I understand correctly, this piece of code relies on some knowledge of how `Ui.modal.iframe` is implemented, namely
that `DismissReason.cancel` or `DismissReason.timer` are not possible?
Why don't we use `if (result.dismiss !== DismissReason.close) ` or simply return boolean from `Ui.modal.iframe()`?

**Review by rrrooommmaaa — CHANGES_REQUESTED** [review]
Looks very neat to me, except for one thing that can be improved.

File: extension/js/common/xss-safe-factory.ts (hunk 1 above)
Comment (limonte) [reply extension/js/common/xss-safe-factory.ts]: > If I understand correctly, this piece of code relies on some knowledge of how `Ui.modal.iframe` is implemented, namely
> that `DismissReason.cancel` or `DismissReason.timer` are not possible?

Correct, we don't use timer or the SweetAlert2's cancel buttons in the passphrase dialog.

> Why don't we use `if (result.dismiss !== DismissReason.close) ` or simply return boolean from `Ui.modal.iframe()`?

Right, it can be as simple as checking `result.dismiss`. If a dialog was closed by `BrowserMsg.send.closeDialog()`, `result.dismiss` will be `undefined`. (docs: https://sweetalert2.github.io/#handling-dismissals)

**Review by rrrooommmaaa — APPROVED** [review]
LGTM!
