### PR TITLE
#5848 Use Manifest V2 for Thunderbird Port

### LINKED ISSUE #5848: Thunderbird (master branch) complains about messageDisplayScript undefined due to possible change of manifest version
Description:

There's an error message saying that the usage of `messageDisplayScript` is undefined.

image

Upon checking, the Thunderbird 91 or older only supports messageDisplayScript for already opened pages https://webextension-api.thunderbird.net/en/91/messageDisplayScripts.html and so it does not work for Thunderbird client version128 ESR version or latest. 

image

So from the latest documentation available at https://webextension-api.thunderbird.net/en/128-esr-mv2/messageDisplayScripts.html, it is suggested to use [executeScript](https://webextension-api.thunderbird.net/en/128-esr-mv2/tabs.html#tabs-executescript) for maximum compatibility possible.

image

### PR DESCRIPTION
**Pull request by martgil**
This PR changes the manifest version used by the Thunderbird Port from v3 to v2 due to unstable support of Thunderbird Typescript typings for Thunderbird ESR 128 and above.

close #5848

issue #5786

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by martgil** [comment]
Hi @sosnovsky - This one is ready for review. All the previous features we have tested before works with no additions or reduction to previously working ones. Thanks!

**Comment by martgil** [comment]
Hi @sosnovsky - I just added some tests from the last commit. It's ready for review again. thanks!

File: tooling/build-types-and-manifests.ts [hunk 1]
```diff
@@ -59,11 +68,13 @@ addManifest(
       default_title: 'Secure Compose', // eslint-disable-line @typescript-eslint/naming-convention
       default_icon: '/img/logo/flowcrypt-logo-64-64.png', // eslint-disable-line @typescript-eslint/naming-convention
     };
+    delete manifest.minimum_chrome_version;
     (manifest.browser_specific_settings as messenger._manifest.FirefoxSpecificProperties).strict_min_version = '102.0';
     manifest.background = {
       type: 'module',
       scripts: ['/js/service_worker/background.js'],
     };
+    manifest.content_scripts?.splice(0, 1);
```
Comment (sosnovsky) [inline tooling/build-types-and-manifests.ts:77]: do we need to remove array item here? I thought we use `content_scripts` for injecting js scripts, but extension works well even after this change

Comment (sosnovsky) [reply tooling/build-types-and-manifests.ts:77]: Hmm, looks like extension works when opened as separate "Encrypted inbox", but doesn't decrypt messages directly in Thunderbird UI, as it's JS files are not injected.

In [thunderbirdContentScriptRegistration](https://github.com/FlowCrypt/flowcrypt-browser/blob/d70bf0f2f8452291ab3c2994d327d7c9ef48830b/extension/js/service_worker/bg-handlers.ts#L156) we extract files from `content_scripts` property, but after this change it contains only `./js/common/oauth2/oauth2_inject.js` and not files needed for processing messages.

Comment (martgil) [reply tooling/build-types-and-manifests.ts]: Thank you for pointing it out @sosnovsky. I made a mistake I guess after this change where everything continue to work on allthroughtout. Retesting it again indeed do not work properly. I revert my changes, close and re-open TB and tested it again.

File: test/source/patterns.ts [hunk 2]
```diff
@@ -98,10 +99,26 @@ for (const buildType of ['chrome-consumer', 'chrome-enterprise']) {
...
+      console.error(`${buildType} - content_security_policy should be a string`);
+      errsFound++;
+    }
+  }
+  if (webBrowserBuilds) {
+    const gmailCs = manifest.content_scripts?.find(cs => cs.matches?.includes('https://mail.google.com/*'));
+    if (!gmailCs?.css?.length || !gmailCs.js?.length) {
+      console.error(`Missing content_scripts declaration for Gmail in ${buildType}/manifest.json`);
+      errsFound++;
+    }
```
Comment (sosnovsky) [inline test/source/patterns.ts:121]: after the latest change for `content_scripts`, I think this test should be applied to thunderbird builds too

File: test/source/patterns.ts [hunk 3]
```diff
@@ -81,11 +81,12 @@ for (const srcFilePath of getAllFilesInDir('./extension', /\.ts$/)) {
...
+for (const buildType of ['chrome-consumer', 'chrome-enterprise', 'thunderbird-consumer', 'firefox-consumer']) {
   const manifest = JSON.parse(readFileSync(`./build/${buildType}/manifest.json`).toString()) as chrome.runtime.Manifest;
+  const webBrowserBuilds = buildType.includes('chrome') || buildType.includes('firefox');
   const expectedHostPermissions = buildType.includes('consumer') ? expectedConsumerHostPermissions : expectedEnterpriseHostPermissions;
   for (const expectedHostPermission of expectedHostPermissions) {
-    if (!manifest.host_permissions.includes(expectedHostPermission)) {
+    if (webBrowserBuilds && !manifest.host_permissions.includes(expectedHostPermission)) {
       console.error(`Missing host permission '${expectedHostPermission}' in ${buildType}/manifest.json`);
       errsFound++;
     }
```
Comment (sosnovsky) [inline test/source/patterns.ts:92]: let's check for permissions in thunderbird builds too, it'll be just `manifest.permissions` array instead of `manifest.host_permissions`:
```ts
const buildHostPermissions = webBrowserBuilds ? manifest.host_permissions : manifest.permissions;
if (!buildHostPermissions.includes(expectedHostPermission)) {
...
}
```

**Review by sosnovsky — COMMENTED** [review]
works well now, thanks!

File: test/source/patterns.ts (hunk 2 above)
Comment (martgil) [reply test/source/patterns.ts]: Thanks for the tip @sosnovsky. I made a little refactor to it as I think it should be described as generic since most builds that will come will likely to be tested for this content_script contents.

File: test/source/patterns.ts (hunk 3 above)
Comment (martgil) [reply test/source/patterns.ts]: Thanks @sosnovsky - I have added a test for this one for the thunderbird build. Would you mind checking it again? Thank you.

**Comment by martgil** [comment]
Hello @sosnovsky, may I request another review? Thank you!

File: test/source/patterns.ts [hunk 4]
```diff
@@ -98,9 +99,51 @@ for (const buildType of ['chrome-consumer', 'chrome-enterprise']) {
...
+      'accountsRead',
+      'https://flowcrypt.com/*',
+      'https://*.google.com/*',
+      'https://outlook.live.com/*',
+      'https://outlook.office365.com/*',
+      'https://outlook.office.com/*',
+      'https://graph.microsoft.com/*',
+      'https://login.microsoftonline.com/*',
+      'https://www.googleapis.com/*',
+    ];
```
Comment (sosnovsky) [inline test/source/patterns.ts:135]: we already checked `expectedPermissions` and `expectedHostPermissions` earlier, here let's check only for Thunderbird specific permissions (`'messagesRead', 'messagesUpdate', 'messagesModify', 'accountsRead'`)

**Comment by martgil** [comment]
Hi @sosnovsky - It is now good to go. thank you!

**Review by sosnovsky — APPROVED** [review]
All good now, thanks!
