### PR TITLE
#4490 fix: no-explicit-any warnings

### LINKED ISSUE #4490: no-explicit-any warnings - prefer unknown
> It seems we have delayed after-effects after this merge. #4284 https://flowcrypt.semaphoreci.com/jobs/47dbcb8e-5bc4-437a-9812-e70699e7d855

They are all warnings, except for 

```
   148:4   error    Missing semicolon                         @typescript-eslint/semi 00:09 
```

In either case, we should try to address these warnings - I'll file an issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4484#issuecomment-1152617605_

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed no-explicit-any warnings

close #4490 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/js/common/api/email-provider/gmail/gmail-parser.ts [hunk 1]
```diff
@@ -126,10 +126,9 @@ export class GmailParser {
   };
 
   public static findBodies = (gmailMsg: GmailRes.GmailMsg | GmailRes.GmailMsg$payload | GmailRes.GmailMsg$payload$part, internalResults: SendableMsgBody = {}): SendableMsgBody => {
-    const isGmailMsgWithPayload = (v: any): v is GmailRes.GmailMsg => v && typeof (v as GmailRes.GmailMsg).payload !== 'undefined'; // tslint:disable-line:no-unsafe-any
-    const isGmailMsgPayload = (v: any): v is GmailRes.GmailMsg$payload => v && typeof (v as GmailRes.GmailMsg$payload).parts !== 'undefined'; // tslint:disable-line:no-unsafe-any
-    // tslint:disable-next-line:no-unsafe-any
-    const isGmailMsgPayloadPart = (v: any): v is GmailRes.GmailMsg$payload$part => v && typeof (v as GmailRes.GmailMsg$payload$part).body !== 'undefined';
+    const isGmailMsgWithPayload = (v: unknown): v is GmailRes.GmailMsg => !!v && typeof (v as GmailRes.GmailMsg).payload !== 'undefined'; // tslint:disable-line:no-unsafe-any
```
Comment (rrrooommmaaa) [inline extension/js/common/api/email-provider/gmail/gmail-parser.ts:129]: do we still need `// tslint:disable-line:no-unsafe-any` on lines 129 and 130?

Comment (ioanmo226) [reply extension/js/common/api/email-provider/gmail/gmail-parser.ts]: We indeed don't need it.

File: extension/js/common/platform/catch.ts [hunk 2]
```diff
@@ -117,10 +117,10 @@ export class Catch {
     return Catch.reportErr(Catch.nameAndDetailsAsException(name, details));
   };
 
-  public static isPromise = (v: any): v is Promise<unknown> => {
-    return v && typeof v === 'object' // tslint:disable-line:no-unsafe-any
-      && typeof (v as Promise<any>).then === 'function' // tslint:disable-line:no-unbound-method - only testing if exists
-      && typeof (v as Promise<any>).catch === 'function'; // tslint:disable-line:no-unbound-method - only testing if exists
+  public static isPromise = (v: unknown): v is Promise<unknown> => {
+    return !!v && typeof v === 'object' // tslint:disable-line:no-unsafe-any
```
Comment (rrrooommmaaa) [inline extension/js/common/platform/catch.ts:121]: looks like we don't need `// tslint:disable-line:no-unsafe-any` on line 121?

**Review by rrrooommmaaa — APPROVED** [review]
