### PR TITLE
#5730 Fix error when sending blank signed message

### LINKED ISSUE #5730: Error when trying to send empty signed-only message
> I noticed just now that when trying to send a blank signed message, there was this unhandled error message that occurred.

image

_Originally posted by @martgil in https://github.com/FlowCrypt/flowcrypt-browser/issues/5599#issuecomment-1940538245_

### PR DESCRIPTION
**Pull request by martgil**
This PR improves the case where sending an empty signed message using FlowCrypt returns unhandled error. This is due to `createCleartextMessage()` not accepting empty message. So passing a newline that would serve as empty message would satify the condition when user choose to send blank signed email when asked by the FlowCrypt browser extension. 

close #5730

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by martgil** [comment]
Hi @sosnovsky, I think this particular one does not need to test for such a small changes. Would you agree on that or should I make another test for sending blank signed message?

File: extension/js/common/core/crypto/pgp/openpgp-key.ts [hunk 1]
```diff
@@ -268,6 +268,7 @@ export class OpenPGPKey {
       const message = await opgp.createMessage({ text });
       return await opgp.sign({ message, format: 'armored', signingKeys: [signingPrv], detached });
     }
+    text = text ? text : '\n';
```
Comment (sosnovsky) [inline extension/js/common/core/crypto/pgp/openpgp-key.ts:271]: Original issue happens because empty string ` ` is equal to `false` in js.
But if we'll create empty string as `String(text)` then it'll be `true`.
So let's just convert original `text` parameter to string (as `String(data)`) at https://github.com/FlowCrypt/flowcrypt-browser/blob/75621567b2ef423461d5363776e556921ff4c86a/extension/js/common/core/crypto/pgp/msg-util.ts#L162

Comment (martgil) [reply extension/js/common/core/crypto/pgp/openpgp-key.ts:271]: Hello @sosnovsky -  That would work too because if `text` is still doesn't hold any string value -- it will still failed to pass the truthy value test check - https://github.com/openpgpjs/openpgpjs/blob/026b348cf87988cf95896dd9c5dd1a0c8129ddb1/src/cleartext.js#L210.

So I think a way to solve this is to put something "invisible" in replacement when the text is completely blank to pass the checks.

Comment (sosnovsky) [reply extension/js/common/core/crypto/pgp/openpgp-key.ts:271]: Yeah, you're right - I initially tested `new String(text)` with raw openpgp.js, but it doesn't work when used in FlowCrypt code. So let's use your solution ✅

**Review by sosnovsky — APPROVED** [review]
👍

File: extension/js/common/core/crypto/pgp/openpgp-key.ts (hunk 1 above)
Comment (martgil) [reply extension/js/common/core/crypto/pgp/openpgp-key.ts:271]: Thanks - Roma, I understand your side now. The way you test it out is also my go to too --- just poping my test enviroment with raw openpgp.js. Thanks for considering the suggested solution.
