### PR TITLE
#5764 Fix long ‘environment’ string

### LINKED ISSUE #5764: Error when trying to send exception from content script
In backend logs there are errors saying `Error processing POST api/v1/log-collector/exception | id: 7d39a4a33f96 | message: ERROR: value too long for type VARCHAR(20)`. I noticed that it's possible to have longer string for `environment` property when it has `ex:script:gmail` value: https://github.com/FlowCrypt/flowcrypt-browser/blob/e6fe45d270efdfabe16631bcb4b4c22c0a9bd0be/extension/js/common/platform/catch.ts#L196

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR makes `environment` string shorter to be valid for `log-collector/exception` endpoint

close #5764

----------------------------------

**Tests** _(delete all except exactly one)_:
- Not worth testing

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/js/common/platform/catch.ts [hunk 1]
```diff
@@ -193,7 +193,7 @@ export class Catch {
     } else if (origin === 'https://flowcrypt.com') {
       env = 'web:prod';
     } else if (origin === 'https://mail.google.com') {
-      env = 'ex:script:gmail';
+      env = 'ex:s:gmail';
     }
```
Comment (martgil) [inline extension/js/common/platform/catch.ts:197]: Hi @sosnovsky - Do you think it's necessary to add comments explaining "env" if it stands for "script"?

Comment (sosnovsky) [reply extension/js/common/platform/catch.ts:197]: I think it's ok to leave it without comment, as currently we use this property only for differentiating environments where exception happened.

Comment (martgil) [reply extension/js/common/platform/catch.ts:197]: Oh, okay - thanks!

**Review by martgil — APPROVED** [review]
