### PR TITLE
#5940 Clean up unused alarms

### LINKED ISSUE #5940: Cleanup Unused Alarms to Prevent Exceeding Limit
I encountered the following error on the extension errors page:

> Uncaught (in promise) Error: An extension cannot have more than 500 active alarms.

It looks like we need to clean up alarms, specifically those used for delete_expired, as they may be accumulating unnecessarily.
This could be causing the extension to exceed the 500 active alarms limit.

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR implemented feature to clean up unused alarms

close #5940 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/js/common/browser/browser-msg.ts [hunk 1]
```diff
@@ -429,10 +429,19 @@ export class BrowserMsg {
...
+        await chrome.alarms.clear(alarm.name);
+      }
+    }
+  }
+
+  public static async createIntervalAlarm(action: string, periodInMinutes: number) {
     const alarmName = `${action}_interval_${Date.now()}`;
 
-    void chrome.alarms.create(alarmName, { periodInMinutes });
+    await chrome.alarms.create(alarmName, { periodInMinutes });
```
Comment (sosnovsky) [inline extension/js/common/browser/browser-msg.ts:444]: `chrome.alarms.create` documentation says `If there is another alarm with the same name (or no name if none is specified), it will be cancelled and replaced by this alarm.`.

What about using `${action}_interval` as name (without timestamp), so existing alarm will be automatically cancelled and replaced with new one?

File: extension/js/common/browser/browser-msg.ts [hunk 2]
```diff
@@ -513,6 +522,7 @@ export class BrowserMsg {
 
   public static alarmListen() {
     const alarmListener = (alarm: { name: string }) => {
+      console.log(alarm.name);
```
Comment (sosnovsky) [inline extension/js/common/browser/browser-msg.ts:525]: can be removed

**Review by sosnovsky — APPROVED** [review]
looks good 👍
