### PR TITLE
Make the 'Secure Compose' button (almost) independent from Gmail styles

### LINKED ISSUE #3558: browser compose button looks broken after Gmail UI update
image

### PR DESCRIPTION
**Pull request by limonte**
This PR places the 'Secure Compose' button under the Gmail logo and makes the styles of the 'Secure Compose' button independent from the layout. Because the layout can be different with different settings, e.g. Meet ebabled/disabled.

close #3558

**Tests**:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
Thank you!

**Comment by tomholub** [comment]
Was there something you wanted to do between the current Draft state and a ready PR?

**Comment by limonte** [comment]
> Was there something you wanted to do between the current Draft state and a ready PR?

Just double-checked everything in all browsers (Chrome/Firefox/Egde).

**Comment by limonte** [comment]
Found one small detail to fix.

**Comment by limonte** [comment]
Should be good now. Tested in Chrome and Firefox for these cases:

- [ ] new UI, Meet enabled, left menu expanded
- [ ] new UI, Meet enabled, left menu collapsed
- [ ] new UI, Meet disabled, left menu expanded
- [ ] new UI, Meet disabled, left menu collapsed
- [ ] old UI, left menu expanded
- [ ] old UI, left menu collapsed (for old UI Meet doesn't change the layout)

File: extension/js/common/inject.ts [hunk 1]
```diff
@@ -46,8 +46,7 @@ export class Injector {
     this.S = Ui.buildJquerySels({ // these are selectors that are not specific to any webmail variant
       body: 'body',
       compose_button_container: this.container.composeBtnSel[this.webmailName],
-      compose_button: 'div.new_message_button',
-      compose_button_label: '#cryptup_compose_button_label',
```
Comment (limonte) [inline extension/js/common/inject.ts:50]: I removed `compose_button_label` because I didn't found its usage in the codebase

**Review by tomholub — APPROVED** [review]
Thank you!
