### PR TITLE
#4532 fix: cache found contacts locally as soon as they are fetched issue

### LINKED ISSUE #4532: cache found contacts locally as soon as they are fetched
ok. On browser extension, we actually do keep a cache and it should be a lot faster the second time. Is it not? Maybe we don't currently cache all, but only cache items that the user actually used. If that's the case, we could start caching all on browser extension too.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1741#issuecomment-1177831585_

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed cache found contacts locally as soon as they are fetched issue

close #4532 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Test added

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
Please review this PR and [issue comments](https://github.com/FlowCrypt/flowcrypt-browser/issues/4532).

**Comment by ioanmo226** [comment]
Also I find that in Gmail app, debounce time is less than 50ms. It shows results as soon as i finish typing.
But in our app, debounce time is set as 500ms. Maybe we can decrease it to 100 or 200ms?

**Comment by ioanmo226** [comment]
@rrrooommmaaa Please check above comment too

**Comment by rrrooommmaaa** [comment]
> But in our app, debounce time is set as 500ms. Maybe we can decrease it to 100 or 200ms?

Maybe we can. I'm not an expert in this.

**Comment by ioanmo226** [comment]
I see. Maybe @tomholub can confirm.
And he confirms, we may do it in another PR.

**Comment by rrrooommmaaa** [comment]
But we need to make sure the new search hasn't started until the previous one has completed. Or that we handle this situation gracefully.

File: extension/chrome/elements/compose-modules/compose-recipients-module.ts [hunk 1]
```diff
@@ -647,7 +644,7 @@ export class ComposeRecipientsModule extends ViewModule<ComposeView> {
       return 0;
     });
     const renderableContacts = sortedContacts.slice(0, this.MAX_CONTACTS_LENGTH);
-    if ((renderableContacts.length > 0 || this.contactSearchInProgress) || !this.googleContactsSearchEnabled) {
+    if (renderableContacts.length > 0 || !this.googleContactsSearchEnabled) {
```
Comment (rrrooommmaaa) [inline extension/chrome/elements/compose-modules/compose-recipients-module.ts:647]: I meant to remove the `if`, make this code run each time. We do need to show `No Contacts Found` at the end of the search, don't we?

Comment (rrrooommmaaa) [reply extension/chrome/elements/compose-modules/compose-recipients-module.ts:647]: Oh we don't. Ok, then.

File: extension/chrome/elements/compose-modules/compose-recipients-module.ts [hunk 2]
```diff
@@ -702,11 +693,16 @@ export class ComposeRecipientsModule extends ViewModule<ComposeView> {
...
-        display: 'none',
+        display: renderableContacts.length > 0 ? 'block' : 'none', // show popup only when there are renderableContacts
         left: leftOffset,
         top: offsetTop,
         maxHeight: `calc(100% - ${offsetTop + bottomGap}px)`,
       });
+    } else {
+      this.view.S.cached('contacts').find('ul').html('<li>No Contacts Found</li>'); // xss-direct
+      if (!this.googleContactsSearchEnabled) {
+        this.addBtnToAllowSearchContactsFromGoogle(input);
```
Comment (ioanmo226) [inline extension/chrome/elements/compose-modules/compose-recipients-module.ts:704]: I changed this logic because with previous logic, when there's search result for something like `e2e` and then user continues type like `e2eaaaaaaaa`, it still displays `e2e` result.

**Comment by ioanmo226** [comment]
@rrrooommmaaa Please review this PR

File: extension/chrome/elements/compose-modules/compose-recipients-module.ts (hunk 2 above)
Comment (rrrooommmaaa) [reply extension/chrome/elements/compose-modules/compose-recipients-module.ts:704]: I have tested it and it's looking ok. So, if `googleContactsSearchEnabled` is `true` and I'm typing a non-existing name `aaaaaa`, nothing is displayed (`No Contacts Found` isn't displayed).
However if I first type an existing name like `flow`, wait until the contacts appear and then continue typing to `flowwww`, then `No Contacts Found` is displayed replacing the found contacts. Is this the desired behaviour?

Comment (ioanmo226) [reply extension/chrome/elements/compose-modules/compose-recipients-module.ts:711]: I don't think so. I just fixed and pushed. Please check

Comment (rrrooommmaaa) [reply extension/chrome/elements/compose-modules/compose-recipients-module.ts:711]: So how should it behave? Can you add a unit test, please? Something like `compose - load contacts through API` but simpler. If we run such a test only for `testVariant === 'ENTERPRISE-MOCK'`, `googleContactsSearchEnabled` will be `true`. You can always find the profile's own email address in contacts, that is `ci.tests.gmail@flowcrypt.test` for `ci.tests.gmail` profile

Comment (ioanmo226) [reply extension/chrome/elements/compose-modules/compose-recipients-module.ts:711]: Current behavior is to show `no contact founds` for all cases when there are no contacts found

Comment (ioanmo226) [reply extension/chrome/elements/compose-modules/compose-recipients-module.ts:711]: This is current implemented behavior.
@tomholub Not sure who can confirm this. Can you confirm if this is what you are looking for? I'll add ui test (as Roman suggested) after your confirmation

chrome-capture-2022-7-9

Comment (tomholub) [reply extension/chrome/elements/compose-modules/compose-recipients-module.ts:711]: behavior-wise, the screen recording looks ok to me. I haven't read the rest of the conversation

Comment (ioanmo226) [reply extension/chrome/elements/compose-modules/compose-recipients-module.ts:713]: @rrrooommmaaa Ready for review

Comment (rrrooommmaaa) [reply extension/chrome/elements/compose-modules/compose-recipients-module.ts:713]: The element added by `addBtnToAllowSearchContactsFromGoogle` remains as a leftover after the "No Contacts Found" case, is this intentional?
The look when a contact is found right away:
image
The look when a contact is found after the "No Contacts Found" case:
image

Comment (ioanmo226) [reply extension/chrome/elements/compose-modules/compose-recipients-module.ts:714]: Thanks for your notice
> The element added by addBtnToAllowSearchContactsFromGoogle remains as a leftover after the "No Contacts Found" case

I don't think so. Just fixed
> is this intentional?

**Review by rrrooommmaaa — APPROVED** [review]
