### PR TITLE
#5493 Remove parameter check in feedback endpoint

### LINKED ISSUE #5493: Error message pops-up when sending a feedback to flowcrypt developers
reported by @martgil:

### Description

An error message pops up when sending feedback to FlowCrypt developers. Upon reviewing the reported issue, I identified that the endpoint `POST https://flowcrypt.com/shared-tenant-fes/api/v1/account/feedback` returns `{}` without the `sent` boolean value that was later parsed in the `help.ts` file to conclude whether the email is sent or not.

### Affected File
https://github.com/FlowCrypt/flowcrypt-browser/blob/27bd910b5edef7bb3e03f4c3518c380fd34d67bf/extension/chrome/settings/modules/help.ts#L76-L80

### Steps to reproduce
1. Using a `@gmail.com` account, open the FlowCrypt browser extension page.
2. From the FlowCrypt Settings Dashboard, click on `Feedback`.
3. Provide sample feedback and click `Send`.
4. You'll get an error message that says `There was an error sending message. Please write us at 
human@flowcrypt.com for support.`

Reference:
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGwHpMwbQjKLkhlvkwjtXcNjlKn

### PR DESCRIPTION
**Pull request by martgil**
This PR removes the `boolean` JSON parameter `sent` in the send user feedback endpoint.

close #5493 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by martgil** [comment]
@sosnovsky Ready for review. thank you!

File: extension/js/common/api/account-servers/external-service.ts [hunk 1]
```diff
@@ -29,7 +29,7 @@ export namespace FesRes {
   };
   export type ServiceInfo = { vendor: string; service: string; orgId: string; version: string; apiVersion: string };
   export type ClientConfiguration = { clientConfiguration: ClientConfigurationJson };
-  export type HelpFeedback = { sent: boolean };
+  export type HelpFeedback = {}; // eslint-disable-line @typescript-eslint/ban-types
```
Comment (sosnovsky) [inline extension/js/common/api/account-servers/external-service.ts:32]: As we expect just empty response, there is no need for separate `HelpFeedback` type - it can be removed. And then `helpFeedback` method should be transformed to:
```ts
public helpFeedback = async (email: string, message: string): Promise<void> => {
    return await this.request(`/api/${this.apiVersion}/account/feedback`, { fmt: 'JSON', data: { email, message } });
};
```

Comment (martgil) [reply extension/js/common/api/account-servers/external-service.ts]: Thank you, Roma. It has now been updated.

**Comment by martgil** [comment]
@sosnovsky ready for review again. thank you!

**Review by sosnovsky — APPROVED** [review]
All good now 👍
