### PR TITLE
#3505 Fix: decode attachment file name

### LINKED ISSUE #3505: Special characters in attachment filenames don't work
### Steps to reproduce:

1. Create a file whose name contains a character not allowed in URL's, like `what's_up?.txt`
2. Send the file via Secure Compose
3. Download the file from the recipient inbox
4. Viola, the filename on your machine will be `what&#39;s_up_.txt`

My guess would be that this filename is decoded from a URL, but a cursory glance at the relevant code didn't immediately reveal anything, so I'm still unsure.

I'll look deeper into this but in the meantime any ideas/suggestions are appreciated :)

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR decodes attachment file name

close #3505 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Review by rrrooommmaaa — COMMENTED** [review]
why doesn't it need a test? We could add a message (to `exported-messages`) that was wrongly rendered previously and correctly rendered now.

File: test/source/tests/browser-unit-tests/unit-Mime.js [hunk 1]
```diff
@@ -338,3 +338,24 @@ BROWSER_UNIT_TEST_NAME(`Mime attachment file name issue 3352`);
   }
   return 'pass';
 })();
+
+BROWSER_UNIT_TEST_NAME(`Mime attachment file name issue #3505`);
+(async () => {
+  const originalName = 'what\'s_up?.txt';
```
Comment (ioanmo226) [inline test/source/tests/browser-unit-tests/unit-Mime.js:344]: @rrrooommmaaa FYI I tried to combine those duplicated code (With above logic) but then I realized I couldn't add custom javascript function in this file as this file is parsed in unit-browser.ts file.

Comment (rrrooommmaaa) [reply test/source/tests/browser-unit-tests/unit-Mime.js:344]: To re-use library code in unit browser tests we should add import into `extension/chrome/dev/ci_unit_test.ts` file and also add the imported instance to `libs` array there, if that's what you're asking.

Comment (ioanmo226) [reply test/source/tests/browser-unit-tests/unit-Mime.js]: Aha, got it
Thanks

File: test/source/tests/browser-unit-tests/unit-Mime.js [hunk 2]
```diff
@@ -320,21 +320,10 @@ BROWSER_UNIT_TEST_NAME(`Mime attachment file names`);
...
-  if (extractedName !== originalName) {
-    throw Error(`extractedName unexpectedly ${extractedName}, expecting ${originalName}`);
-  }
-  return 'pass';
+  return await Mime.checkAttachmentDecode('XX J 1 IT E (P 4) p_c.pdf');
+})();
+
+BROWSER_UNIT_TEST_NAME(`Mime attachment file name issue #3505`);
+(async () => {
+  return await Mime.checkAttachmentDecode('what\'s_up?.txt');
```
Comment (rrrooommmaaa) [inline test/source/tests/browser-unit-tests/unit-Mime.js:328]: not quite clear how this test covers `XssSafeFactory.srcPgpAttachmentIframe` method.
Can you please provide a `eml`-formatted message with this attachment? We can then convert it to our `json` format for testing.

**Review by rrrooommmaaa — CHANGES_REQUESTED** [review]

File: test/source/tests/browser-unit-tests/unit-Mime.js (hunk 2 above)
Comment (rrrooommmaaa) [reply test/source/tests/browser-unit-tests/unit-Mime.js:328]: if you have it in a gmail inbox, it's even easier. EML is not needed. You need to have Flowcrypt extension installed for this account and...
https://github.com/FlowCrypt/flowcrypt-browser/blob/fae2bb7d00555a53713cb13c2300b54ff29c3aa6/test/source/mock/google/google-data.ts#L102:L106

Comment (rrrooommmaaa) [reply test/source/tests/browser-unit-tests/unit-Mime.js:328]:
```
   * This is the proper way to add messages to mock api for testing:
   *   1) log into flowcrypt.compatibility@gmail.com
   *   2) go to Settings -> Inbox and find your message
   *   3) click "download api export"
   *   4) save the json file to exported-messages folder
```

Comment (ioanmo226) [reply test/source/tests/browser-unit-tests/unit-Mime.js:328]: Got it. Thank you

File: extension/js/common/browser/browser.ts [hunk 3]
```diff
@@ -27,7 +26,7 @@ export class Browser {
     const blob = new Blob([attachment.getData()], { type: attachment.type });
     const a = window.document.createElement('a');
     a.href = window.URL.createObjectURL(blob);
-    a.download = Xss.escape(attachment.name);
+    a.download = attachment.name;
```
Comment (ioanmo226) [inline extension/js/common/browser/browser.ts:29]: @rrrooommmaaa FYI This escape function converted special characters to something like `&quot;` and as I checked it's not needed for `download` a tag.

File: extension/chrome/elements/attachment.ts [hunk 4]
```diff
@@ -79,9 +79,10 @@ export class AttachmentDownloadView extends View {
       return;
     }
     $('#type').text(this.type || 'unknown type');
-    $('#name').text(this.name || 'noname');
+    const attachmentName = decodeURIComponent(this.name || 'noname');
```
Comment (rrrooommmaaa) [inline extension/chrome/elements/attachment.ts:82]: Are you sure we need this extra decoding? 
I sent a message with an attachment name `what's_up%253F.txt`
When downloaded, the file name became `what's_up%3F.txt`
(I committed the message 182263bf9f105adf to the repo)
Please add a test that the downloaded file name matches the initial one.

File: test/source/tests/settings.ts [hunk 5]
```diff
@@ -506,6 +506,20 @@ export const defineSettingsTests = (testVariant: TestVariant, testWithBrowser: T
       Util.deleteFileIfExists(downloadedAttachmentFilename);
     }));
 
+    ava.default('settings - check if downloaded attachment name is correct', testWithBrowser('compatibility', async (t, browser) => {
+      // `what's up?.txt` becomes `what's_up_.txt` and this is native way and we can't change this logic
+      // https://github.com/FlowCrypt/flowcrypt-browser/issues/3505#issuecomment-812269422
+      const downloadedAttachmentFilename = `${__dirname}/what\'s_up_.txt`;
+      const inboxPage = await browser.newPage(t, TestUrls.extension(`chrome/settings/inbox/inbox.htm?acctEmail=flowcrypt.compatibility@gmail.com&threadId=1821bf879a6f71e0`));
+      // @ts-ignore
+      await (inboxPage.target as Page)._client.send('Page.setDownloadBehavior', { behavior: 'allow', downloadPath: __dirname });
```
Comment (rrrooommmaaa) [inline test/source/tests/settings.ts:515]: I'd very much like to re-use the method `awaitDownloadTriggeredByClicking` that we have in `controllable.ts`, rather than making copies this low-level code.
We could make `awaitDownloadTriggeredByClicking` return filenames as well and probably an option to include the file contents (so we can turn it off when it's not required)

File: extension/js/common/xss-safe-factory.ts [hunk 6]
```diff
@@ -134,7 +134,7 @@ export class XssSafeFactory {
       a.url = Browser.objUrlCreate(a.getData());
     }
     return this.frameSrc(this.extUrl(iframeUrl), {
-      frameId: this.newId(), msgId: a.msgId, name: a.name, type: a.type, size: a.length, attachmentId: a.id, url: a.url, isEncrypted, errorDetailsOpened, initiatorFrameId
+      frameId: this.newId(), msgId: a.msgId, name: decodeURIComponent(a.name), type: a.type, size: a.length, attachmentId: a.id, url: a.url, isEncrypted, errorDetailsOpened, initiatorFrameId
```
Comment (rrrooommmaaa) [inline extension/js/common/xss-safe-factory.ts:137]: or this decoding?

File: extension/chrome/elements/attachment.ts (hunk 4 above)
Comment (ioanmo226) [reply extension/chrome/elements/attachment.ts:82]: You are right. We actually don't need this encoding.

File: extension/js/common/xss-safe-factory.ts (hunk 6 above)
Comment (ioanmo226) [reply extension/js/common/xss-safe-factory.ts:137]: No. Thanks for your notice

File: test/source/tests/settings.ts (hunk 5 above)
Comment (ioanmo226) [reply test/source/tests/settings.ts:515]: Thank you for your suggestion, That method seems what I was looking for.

File: test/source/tests/settings.ts [hunk 7]
```diff
@@ -506,6 +508,23 @@ export const defineSettingsTests = (testVariant: TestVariant, testWithBrowser: T
       Util.deleteFileIfExists(downloadedAttachmentFilename);
     }));
 
+    const checkIfFileDownloadCorrectly = async (t: AvaContext, browser: BrowserHandle, threadId: string, fileName: string) => {
```
[the remark this answers is not in the document]
Comment (ioanmo226) [reply test/source/tests/settings.ts:511]: Yeah. sure. it sounds better.

**Review by rrrooommmaaa — APPROVED** [review]

File: test/source/mock/google/exported-messages/message-export-1821bf879a6f71e0.json [hunk 8]
```diff
@@ -0,0 +1,122 @@
...
+          }
+        },
+        {
+          "partId": "1",
+          "mimeType": "application/octet-stream",
+          "filename": "\"what\"'s_up%3F.txt.pgp",
```
Comment (rrrooommmaaa) [inline test/source/mock/google/exported-messages/message-export-1821bf879a6f71e0.json:70]: Looks like google doesn't like this apostrophe in the middle of the file name (between `what` and `s_up`
```
Content-Disposition: attachment;
 filename*0*=utf-8''what's_up%25253F.txt.pgp
```
Probably this is why extra double quotes appear
image
```
        {
          "partId": "1",
          "mimeType": "application/octet-stream",
          "filename": "\"what\"'s_up%3F.txt.pgp",
```

According to https://datatracker.ietf.org/doc/html/rfc2231#section-3
the apostrophe has special meaning like in this example
```
 title*0*=us-ascii'en'This%20is%20even%20more%20
```
we have the 2 required apostrophes right after `utf-8` denoting unspecified language, that's ok, but we should probably escape the apostrophe with %27, so we can take the filename directly from Gmail API (when decoding).
If the filename was encoded like this by the browser extension, we should also fix the encoding part.
@sosnovsky ?

Comment (sosnovsky) [reply test/source/mock/google/exported-messages/message-export-1821bf879a6f71e0.json:70]: @rrrooommmaaa I just checked this message in `flowcrypt.compatibility` account and attachment has correct name in default Gmail view and in decoded FlowCrypt view:

Screenshot 2023-05-12 at 21 39 04

Screenshot 2023-05-12 at 21 40 31

Not clear, what should be fixed here

Comment (rrrooommmaaa) [reply test/source/mock/google/exported-messages/message-export-1821bf879a6f71e0.json:70]: There aren't double quotes around "what" in the MIME message
```
------sinikael-?=_1-16583266435440.5429396972265759
Content-Type: application/octet-stream; name="what's_up?.txt.pgp"
Content-Disposition: attachment; filename*0*=utf-8''what's_up%3F.txt.pgp
```
My guess is that Gmail added them because the apostrophe isn't allowed in the `Content-Disposition: ...` line
We should try `Content-Disposition: attachment; filename*0*=utf-8''what%27s_up%3F.txt.pgp` instead.
Gmail also didn't decode %3F, probably because of the same reason.

Comment (sosnovsky) [reply test/source/mock/google/exported-messages/message-export-1821bf879a6f71e0.json:70]: Ah, now I see that original file name is `what's_up?.txt`, initially I thought quotes were included in original file name.
Thanks for explanation, filing an issue for it
