### PR TITLE
#4513 fix: PUT rename /v1/end-user/key-pairs field

### LINKED ISSUE #4513: PUT /v1/end-user/key-pairs field renamed
used to be `decryptedPrivateKey` and now it's just `privateKey`. Need to update mocks too. Happened here https://github.com/FlowCrypt/flowcrypt-enterprise-on-prem/pull/3043/files

I think that change was unintentional in that PR for end-user API (I overlooked it in my review, anyway), but since we don't have any customer currently using that API, we can leave it on on-prem and update it here, even if that causes incompatibility between previous extension versions and the new on-prem version.

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR renamed PUT /v1/end-user/key-pairs field

close #4513 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
fixed

File: test/source/tests/setup.ts [hunk 1]
```diff
@@ -625,8 +625,6 @@ AN8G3r5Htj8olot+jm9mIa5XLXWzMNUZgg==
       await myKeyFrame.waitAll('@content-fingerprint');
       const fromKm = MOCK_KM_LAST_INSERTED_KEY[acct];
       expect(fromKm).to.exist;
-      const k = await KeyUtil.parse(fromKm.publicKey);
-      expect(await myKeyFrame.read('@content-fingerprint')).to.equal(Str.spaced(k.id));
```
Comment (tomholub) [inline test/source/tests/setup.ts:629]: You can bring these two back, but use `fromKm.privateKey`. Public and private keys in a key pair have the same id (fingerprint). So you can use either to test the UI.

File: test/source/tests/setup.ts [hunk 2]
```diff
@@ -695,8 +693,6 @@ AN8G3r5Htj8olot+jm9mIa5XLXWzMNUZgg==
         await myKeyFrame.waitAll('@content-fingerprint');
         const fromKm = MOCK_KM_LAST_INSERTED_KEY[acct];
         expect(fromKm).to.exist;
-        const k = await KeyUtil.parse(fromKm.publicKey);
-        expect(await myKeyFrame.read('@content-fingerprint')).to.equal(Str.spaced(k.id));
```
Comment (tomholub) [inline test/source/tests/setup.ts:699]: Same here

**Review by tomholub — COMMENTED** [review]
👍 see comments

**Review by tomholub — DISMISSED** [review]

**Comment by tomholub** [comment]
Not sure why different id now, maybe I made a new key for demo instead of recovering.

This should be it now 09977F6F512CA5AD76F0C210248B60EB6D044DF8 you'll just need to space each 4 chars.

**Review by tomholub — APPROVED** [review]
