### PR TITLE
#6056 Fix live gmail tests

### LINKED ISSUE #6056: Fix live Gmail tests
There are several live Gmail tests, which are failing (https://flowcrypt.semaphoreci.com/jobs/ae048b9a-c51b-4402-b6b4-da35526358e5):

```
FAILED test, finalize for mail.google.com - saving and rendering compose drafts when offline 09:49
FAILED test, finalize for mail.google.com - multiple compose windows, saving/opening compose draft 20:36
FAILED test, finalize for mail.google.com - plain reply draft 26:06
FAILED test, finalize for mail.google.com - switch to encrypted forward 46:56
FAILED test, finalize for mail.google.com - plain reply with dot menu 51:27
```

Need to check if it affects only tests, or our real extension functionality is affected too.

### PR DESCRIPTION
**Pull request by ioanatflowcrypt**
This PR fixed live gmail tests

close #6056 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: test/source/tests/tooling/browser-recipe.ts [hunk 1]
```diff
@@ -75,7 +75,7 @@ export class BrowserRecipe {
       // close announcement about updated UI
       await googleChatPage.waitAndClick('.fKz7Od', { delay: 1 });
     }
-    await googleChatPage.waitAny(['a.gb_6d', 'a.gb_Fc', 'a.gb_9d']); // Google hangout logo
+    await googleChatPage.waitAny(['a.gb_6d', 'a.gb_Fc', 'a.gb_9d', 'a.gb_7d']); // Google hangout logo
```
Comment (sosnovsky) [inline test/source/tests/tooling/browser-recipe.ts:78]: looks like they just change number in `a.gb_*d` selector :)

**Review by sosnovsky — APPROVED** [review]
👍

File: test/source/tests/tooling/browser-recipe.ts (hunk 1 above)
Comment (ioanatflowcrypt) [reply test/source/tests/tooling/browser-recipe.ts:78]: Yep. And FYI other test failed because of Google workspace smart features introduce.

image
