### PR TITLE
#5868 Display warning for incorrect pgp checksum

### LINKED ISSUE #5868: Display warning for incorrect PGP checksum
Got it, then let's stick with the newest spec and update test to expect decrypted message text.

By the way, is there any possibility to find if message has incorrect checksum?
Then we at least be able to show some warning about checksum issue

_Originally posted by @sosnovsky in https://github.com/FlowCrypt/flowcrypt-browser/issues/5866#issuecomment-2493073744_

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR implemented feature to display warning for incorrect pgp checksum

close #5868 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
image

File: extension/js/common/message-renderer.ts [hunk 1]
```diff
@@ -521,7 +521,8 @@ export class MessageRenderer {
     sigResult: VerifyRes | undefined,
     renderModule: RenderInterface,
     retryVerification: (() => Promise<VerifyRes | undefined>) | undefined,
-    plainSubject: string | undefined
+    plainSubject: string | undefined,
+    isCheckSumInvalid = false
```
Comment (sosnovsky) [inline extension/js/common/message-renderer.ts:525]: let's call it `isChecksumInvalid` instead of `isCheckSumInvalid`, as `checksum` is a single word, and we already call it this way in `validateChecksum`

File: extension/chrome/elements/pgp_block_modules/pgp-block-render-module.ts [hunk 2]
```diff
@@ -46,14 +46,17 @@ export class PgpBlockViewRenderModule {
...
     let contentWithLink = linkifyHtml(htmlContent);
 
     // Temporary workaround for an issue where 'cryptup_reply' divs are not being hidden when replying to all
     // messages from the FES. The root cause is that FES currently returns the body of
     // password message replies as 'text/plain', which does not hide the divs as intended.
     // This workaround can be safely removed once the FES is updated to return the body of message replies as 'text/html'.
     // https://github.com/FlowCrypt/flowcrypt-browser/issues/5004
+    if (isCheckSumInvalid) {
+      contentWithLink = `<div class="pgp-invalid-checksum">${Lang.pgpBlock.invalidCheckSum}</div>${contentWithLink}}`;
+    }
```
Comment (sosnovsky) [inline extension/chrome/elements/pgp_block_modules/pgp-block-render-module.ts:59]: let's move `if (isCheckSumInvalid) {` check above `temporary workaround` comment, as currently it looks like a part of this workaround and should be removed after FES will send `text/html` messages

File: extension/js/common/core/crypto/key.ts [hunk 3]
```diff
@@ -489,6 +489,60 @@ export class KeyUtil {
     return keys.map(k => ({ id: k.id, emails: k.emails, armored: KeyUtil.armor(k), family: k.family }));
   }
 
+  public static validateChecksum = (armoredText: string): boolean => {
```
Comment (sosnovsky) [inline extension/js/common/core/crypto/key.ts:492]: well done with this validation, works great 👍

File: extension/js/common/message-renderer.ts (hunk 1 above)
Comment (ioanmo226) [reply extension/js/common/message-renderer.ts:525]: Sounds good!

**Review by sosnovsky — APPROVED** [review]
👍
