### PR TITLE
Remove fixed heigth from #attachments .attachment

### LINKED ISSUE #2644: Long filenames of attachments are overflowing their containers
Actual: 

image

Expected

image

### PR DESCRIPTION
**Pull request by limonte**
Fixes #2644 

Visible filenames are limited to 100 chars. Here's the simulated example:

image

### CODE REVIEW

**Comment by limonte** [comment]
I just realize that the second commit isn't right, let me fix it

**Comment by limonte** [comment]
ready for review :+1:

File: extension/chrome/elements/pgp_block_modules/pgp-block-attachmens-module.ts [hunk 1]
```diff
@@ -24,9 +24,10 @@ export class PgpBlockViewAttachmentsModule {
     this.includedAtts = atts;
     for (const i of atts.keys()) {
       const name = (atts[i].name ? Xss.escape(atts[i].name) : 'noname').replace(/\.(pgp|gpg)$/, '');
+      const nameVisible = name.length > 100 ? name.slice(0, 100) + '…' : name;
       const size = Str.numberFormat(Math.ceil(atts[i].length / 1024)) + 'KB';
-      const htmlContent = `<b>${Xss.escape(name)}</b>&nbsp;&nbsp;&nbsp;${size}<span class="progress"><span class="percent"></span></span>`;
-      Xss.sanitizeAppend('#attachments', `<div class="attachment" index="${Number(i)}">${htmlContent}</div>`);
+      const htmlContent = `<b>${nameVisible}</b>&nbsp;&nbsp;&nbsp;${size}<span class="progress"><span class="percent"></span></span>`;
```
Comment (tomholub) [inline extension/chrome/elements/pgp_block_modules/pgp-block-attachmens-module.ts]: Here you should be using `Xss.escape` when inserting untrusted content (sent by another person)

File: extension/chrome/elements/pgp_block_modules/pgp-block-attachmens-module.ts [hunk 2]
```diff
@@ -24,9 +24,10 @@ export class PgpBlockViewAttachmentsModule {
...
+      Xss.sanitizeAppend('#attachments', `<div class="attachment" title="${name}" index="${Number(i)}">${htmlContent}</div>`);
```
Comment (tomholub) [inline extension/chrome/elements/pgp_block_modules/pgp-block-attachmens-module.ts]: Also the `name` here should be xss escaped.

File: extension/chrome/elements/pgp_block_modules/pgp-block-attachmens-module.ts (hunk 1 above)
Comment (limonte) [reply extension/chrome/elements/pgp_block_modules/pgp-block-attachmens-module.ts]: I believe you're reviewing the outdated code.

Comment (limonte) [reply extension/chrome/elements/pgp_block_modules/pgp-block-attachmens-module.ts]: image
