### PR TITLE
#4700 Fix mock test

### LINKED ISSUE #4700: Fix `passphrase should expire in in_memory_pass_phrase_session_length` mock test issue
This test sometimes fails with below error.
Need to fix.

>   ✖ user@passphrase-session-length-client-configuration.flowcrypt.test - passphrase should expire in in_memory_pass_phrase_session_length [ALL RETRIES FAILED for user@passphrase-session-length-client-configuration.flowcrypt.test - passphrase should expire in in_memory_pass_phrase_session_length]
>     ℹ (attempt 1 of 3) Retrying: AssertionError: expected undefined to equal '1234'
>     ℹ (attempt 2 of 3) Retrying: AssertionError: expected undefined to equal '1234'
>     ℹ (attempt 3 of 3) Failed:   /home/semaphore/git/flowcrypt-browser/test/source/tests/setup.ts:853
>             expect(savedPassphrase).to.be.equal(passphrase);

>       AssertionError: expected undefined to equal '1234'
>           at <anonymous> (/home/semaphore/git/flowcrypt-browser/test/source/tests/setup.ts:853:37)
>           at <anonymous> (/home/semaphore/git/flowcrypt-browser/test/source/test.ts:76:7)
>           at <anonymous> (/home/semaphore/git/flowcrypt-browser/test/source/browser/browser-pool.ts:144:61)
>           at <anonymous> (/home/semaphore/git/flowcrypt-browser/test/source/test.ts:71:5)
>           at <async> <anonymous> (/test/source/tests/setup.ts:832:180)
>           at <async> <anonymous> (../test/source/test.ts:71:53)
>           at <async> <anonymous> (/test/source/browser/browser-pool.ts:144:49)

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed `passphrase should expire in in_memory_pass_phrase_session_length` mock test issue

close #4700 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: test/source/mock/backend/backend-data.ts [hunk 1]
```diff
@@ -97,7 +97,7 @@ export class BackendData {
         "flags": [
           "FORBID_STORING_PASS_PHRASE",
         ],
-        "in_memory_pass_phrase_session_length": 3
+        "in_memory_pass_phrase_session_length": 10
```
Comment (ioanmo226) [inline test/source/mock/backend/backend-data.ts:100]: Increased session length because when tests run serially in semaphoreci, passphrase might expire(3 seconds length) before getting passphrase.

**Review by tomholub — APPROVED** [review]
