### PR TITLE
#5770 Fix: message loading stuck issue

### LINKED ISSUE #5770: Message loading is stuck in Firefox
When trying to open encrypted message in Firefox - it just stucks on `Loading...` label and browser hangs out.

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed message loading stuck issue

close #5770 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Difficult to test (Couldn't reproduce in ci environment)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/js/common/browser/browser-msg.ts [hunk 1]
```diff
@@ -321,7 +321,10 @@ export class BrowserMsg {
       BrowserMsg.sendCatch(dest, 'pgp_block_render', bm);
     },
     pgpBlockReady: (frame: ChildFrame, bm: Bm.PgpBlockReady) => {
-      BrowserMsg.sendToParentWindow(frame, 'pgp_block_ready', bm);
+      Catch.setHandledTimeout(() => {
+        // Adding a timeout here because the parent frame might not be ready immediately to receive the event
+        BrowserMsg.sendToParentWindow(frame, 'pgp_block_ready', bm);
+      }, 2000);
```
Comment (ioanmo226) [inline extension/js/common/browser/browser-msg.ts:327]: @sosnovsky, I've identified the reason some messages are getting stuck during loading.

The issue arises because sometimes `PgpBlockView.setHandlers` is called before `Inbox.setHandlers`/`setup-webmail-content-script.browserMsgListen`.
As a result, when `PgpBlockView.setHandlers` tries to send `BrowserMsg.send.pgpBlockReady`, `Inbox.setHandlers` isn't set up to listen to this event yet.
I know adding a 2-second static delay seems like a makeshift solution, and I'm not entirely convinced it's the best approach. I'm looking into alternative solutions now.

What are your thoughts? Also, could you test this PR to see if you can replicate the loading issue?


https://github.com/FlowCrypt/flowcrypt-browser/blob/2b2c2599c9258457aa2ac8da7fff8ce46cb8ed9f/extension/chrome/settings/inbox/inbox.ts#L100
https://github.com/FlowCrypt/flowcrypt-browser/blob/9fa013af570f6d74846b622fc0a344cece3d1d2f/extension/chrome/elements/pgp_block.ts#L68
https://github.com/FlowCrypt/flowcrypt-browser/blob/65387ffdb475e38efa3ed82005052d92ccfc1339/extension/js/content_scripts/webmail/generic/setup-webmail-content-script.ts#L225

Comment (sosnovsky) [reply extension/js/common/browser/browser-msg.ts:327]: This 2-second delay seems to fix issue for me too, however it makes loading of all messages quite long.
It'll be great to find some way for checking if `browserMsgListen` and `setHandlers` were performed before sending messages, or maybe retrying message sending if it wasn't handled.

Interesting why initial issue happens only in `encrypted inbox` and in firefox gmail page, and works well in chrome gmail page. Can be some differences in message sending logic.

File: extension/js/content_scripts/webmail/generic/setup-webmail-content-script.ts [hunk 2]
```diff
@@ -263,6 +263,7 @@ export const contentScriptSetupIfVacant = async (webmailSpecific: WebmailSpecifi
         appendAfter.after(factory.embeddedPubkey(armoredPubkey, false)); // xss-safe-value
       }
     });
+    BrowserMsg.send.setHandlerReadyForPGPBlock('broadcast');
     BrowserMsg.listen(tabId);
```
Comment (sosnovsky) [inline extension/js/content_scripts/webmail/generic/setup-webmail-content-script.ts:267]: probably `BrowserMsg.send.setHandlerReadyForPGPBlock('broadcast');` should be after `BrowserMsg.listen(tabId)`, so it'll be sent after `chrome.runtime.onMessage.addListener` is executed?

**Review by sosnovsky — COMMENTED** [review]
Nice simple solution, seems to work well for me 👍

File: extension/js/content_scripts/webmail/generic/setup-webmail-content-script.ts (hunk 2 above)
Comment (ioanmo226) [reply extension/js/content_scripts/webmail/generic/setup-webmail-content-script.ts:267]: Sounds good

**Review by sosnovsky — APPROVED** [review]
Well done 👍
