### PR TITLE
fix timeout race

### LINKED ISSUE #5263: race with timeoutPromise sometimes fails (the process gets stuck)
A worker promise may not give a turn to other promises, regardless having `await` statements in a loop.

I discovered this in `awaitDownloadTriggeredByClicking`, other cases need to be reviewed too.

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
This PR fixed timeout race in awaitDownloadTriggeredByClicking

close #5263

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (internal test infrastructure fix)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: test/source/browser/controllable.ts [hunk 1]
```diff
@@ -529,8 +529,15 @@ abstract class ControllableBase {
...
-          files[filename] = fs.readFileSync(path.resolve(downloadPath, filename));
+        if (newFilenames.length) {
+          for (const filename of newFilenames) {
+            const filepath = path.resolve(downloadPath, filename);
+            files[filename] = fs.readFileSync(filepath);
+            fs.unlinkSync(filepath);
+          }
+        } else {
+          // Give a turn to other promises, including timeoutPromise
+          await new Promise(resolve => setImmediate(resolve));
```
Comment (rrrooommmaaa) [inline test/source/browser/controllable.ts:540]: This is a hack that is guaranteed to give a turn to timeoutPromise.
Though in this particular case, we'd better use `await Util.sleep`, as the code is going to read the directory without pauses

@sosnovsky ?

Comment (sosnovsky) [reply test/source/browser/controllable.ts:540]: Where we should use `await Util.sleep` here, instead of `await new Promise(resolve => setImmediate(resolve))`?

Comment (rrrooommmaaa) [reply test/source/browser/controllable.ts:540]: We should use `sleep` because otherwise the filesystem will be queried unnecessary often (pausing only for the period of execution of some async Javascript code in the testing process).
In the current `master` it is queried in a loop (if no `.crdownload` files are found) without even allowing other async Javascript code to run. The hack solves the timeout issue, but a little pause would make sense, I guess.
The question is: how many millis?

Comment (sosnovsky) [reply test/source/browser/controllable.ts:540]: Ah, I see now, thanks, what about `500ms`?

**Review by sosnovsky — APPROVED** [review]
👍
