### PR TITLE
Fix resizing draft compose window after entering passphrase in Firefox

### LINKED ISSUE #4139: button out of view after enterpring pass phrase for a draft
1) no pass phrase entered
2) open a new message draft from drafts
3) prompted for pass phrase
4) enter pass phrase, enter
5) draft renders but compose button out of sight (on a 13" macbook / Firefox). Should re-evaluate height after rendering draft post-passphrase-entry

### PR DESCRIPTION
**Pull request by limonte**
This PR fixes the vertical resizing of the compose window in Firefox after entering passphrase for a draft.

close #4139

Also, outside of the scope of the issue, I fixed live gmail tests as they are failing on the `master` branch now.

----------------------------------

**Tests** _(delete all except exactly one)_:
- Not worth testing

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: test/source/tests/gmail.ts [hunk 1]
```diff
@@ -188,14 +189,16 @@ export const defineGmailTests = (testVariant: TestVariant, testWithBrowser: Test
     }));
 
     ava.default('mail.google.com - rendering attachmnents', testWithBrowser('ci.tests.gmail', async (t, browser) => {
-      const gmailPage = await openGmailPage(t, browser, '/FMfcgzGkbDXBWBWBfVKHssLtMqvDQSWN');
```
Comment (limonte) [inline test/source/tests/gmail.ts:191]: For some weird reason this stopped working, it opens the list of emails instead of particular thread.

The fix is to open inbox, then wait 0.5s, then open a thread.

**Review by rrrooommmaaa — APPROVED** [review]
