### PR TITLE
#5838 Added checks for RichText() before initializing squire in Secure Reply message box

### LINKED ISSUE #5838: Incorrect newlines when composing reply message
- go to `flowcrypt.compatibility` inbox
- open `#5466 unencrypted reply` thread
- expand first message
- click `secure reply` on first message toolbar
- type "Hello<kbd>Enter</kbd>World"
- you'll get
```
World
Hello
```

@martgil you already fixed same issue in https://github.com/FlowCrypt/flowcrypt-browser/pull/5729, maybe similar fix will work here too.

### PR DESCRIPTION
**Pull request by martgil**
This PR fixes squire initialization for secure compose message box where newlines gets injected above the current line when `Enter` is pressed.

close #5838 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by martgil** [comment]
Hi @sosnovsky - this one is ready for review. Thank you!

File: extension/chrome/elements/compose-modules/compose-input-module.ts [hunk 1]
```diff
@@ -40,7 +40,9 @@ export class ComposeInputModule extends ViewModule<ComposeView> {
       'click',
       this.view.setHandler(el => this.actionAddIntroHandler(el), this.view.errModule.handle(`add intro`))
     );
-    this.initSquire(this.isRichText());
+    if (this.isRichText()) {
+      this.initSquire(true);
+    }
```
Comment (sosnovsky) [inline extension/chrome/elements/compose-modules/compose-input-module.ts:45]: in this case Squire probably won't be re-initialized when user turns off rich text mode?

I think it'll be better to use `removeRichTextFormatting` here, which checks if `isRichText` is enabled before re-initializing squire:
```ts
this.isRichText() ? this.addRichTextFormatting() : this.removeRichTextFormatting();
```

Comment (martgil) [reply extension/chrome/elements/compose-modules/compose-input-module.ts]: Hi @sosnovsky - I missed this scenario but I have corrected it now.

**Comment by martgil** [comment]
Hi @sosnovsky - Greetings. May I request for another review. thank you!

File: extension/chrome/elements/compose-modules/compose-input-module.ts [hunk 2]
```diff
@@ -36,11 +36,11 @@ export class ComposeInputModule extends ViewModule<ComposeView> {
   }
 
   public setHandlers = () => {
+    this.toggleRichTextFormatting();
```
Comment (sosnovsky) [inline extension/chrome/elements/compose-modules/compose-input-module.ts:39]: `toggleRichTextFormatting` sounds like we change rich text property here, but we just configure textarea according to the existing property value. 
`configureRichTextFormatting` is more correct naming, as for me.

Comment (martgil) [reply extension/chrome/elements/compose-modules/compose-input-module.ts]: Ah, I see. I agree with your suggestion and have changed the name as recommended. Thanks!

**Review by sosnovsky — APPROVED** [review]
All good now, thanks!

**Comment by martgil** [comment]
thank you, too.
