### PR TITLE
#4681 fix: visual glitch opening passphrase dialog

### LINKED ISSUE #4681: Visual glitch opening passphrase dialog
I noticed that the default `<h1>` text "Enter FlowCrypt pass phrase to read encrypted email" is visible for a second,
and then gets replaced with a correct text based on query arguments.
https://github.com/FlowCrypt/flowcrypt-browser/blob/754e0b6d7a453b7ca0fd12672fa806b7d32298e7/extension/chrome/elements/passphrase.htm#L21

(I saw this effect with `update_key` tests, perhaps, the same effect happens for all the other cases)
https://github.com/FlowCrypt/flowcrypt-browser/blob/754e0b6d7a453b7ca0fd12672fa806b7d32298e7/extension/chrome/elements/passphrase.ts#L79

I think it'd be good to display the correct text at once.

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed visual glitch opening passphrase dialog

close #4681 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: extension/js/common/core/common.ts [hunk 1]
```diff
@@ -362,4 +362,8 @@ export const asyncSome = async<T>(arr: Array<T>, predicate: (e: T) => Promise<bo
     if (await predicate(e)) return true;
   }
   return false;
+};
+
+export const stringTuple = <T extends [string] | string[]>(...data: T): T => {
```
Comment (rrrooommmaaa) [inline extension/js/common/core/common.ts:367]: Wouldn't `<T extends string[]>` do?
I see no benefit of `| [string]`

Comment (ioanmo226) [reply extension/js/common/core/common.ts]: You are right. 👍 
Just updated

**Review by rrrooommmaaa — APPROVED** [review]
