### PR TITLE
#5316 Introduce OAuth Class

### LINKED ISSUE #5335: [Needs help] Moving a typescript file to other directory + updated import paths leads to Class as not defined
Description: I'm working with #5316 and having some trouble after updating the google-auth.ts and create oauth.ts file. The old pr that I published is https://github.com/FlowCrypt/flowcrypt-browser/pull/5326 - it complains about GoogleAuth being not defined.

I have done several debugging and I'm clueless why is that. So I had created a fresh PR https://github.com/FlowCrypt/flowcrypt-browser/pull/5334 with changes to just move the google-auth.ts to  common/api/authentication but the error about GoogleAuth being undefined that occurs in `Google.gmailCall()` even though the import paths where correctly updated.

Stack trace:

```
webmail_bundle.js:70 ReferenceError: GoogleAuth is not defined
    at Google.gmailCall (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:8911:48)
    at Gmail.msgGet (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:8482:37)
    at Downloader.msgGetFull (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:10989:46)
    at chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:11665:75
    at MessageRenderer.msgGetProcessed (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:11670:23)
    at GmailElementReplacer.replaceArmoredBlocks (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13826:79)
    at GmailElementReplacer.everything (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13801:18)
    at Object.handler (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13735:55)
    at Object.start (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:15238:46)
    at async entrypoint (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:15060:21)
    at <async> gmailCall (/extension/js/common/api/email-provider/gmail/google.ts:18:28)
    at <async> msgGet (/extension/js/common/api/email-provider/gmail/gmail.ts:110:18)
    at <async> msgGetFull (/extension/js/common/downloader.ts:53:22)
    at <async> <anonymous> (/extension/js/common/message-renderer.ts:391:20)

### Catch.reportErr calling stack ###
#     at Catch.formatExceptionForReport (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:279:90)
#     at Catch.onErrorInternalHandler (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:87:29)
#     at Catch.reportErr (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:103:18)
#     at GmailElementReplacer.handleException (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:14274:27)
#     at GmailElementReplacer.replaceArmoredBlocks (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13829:30)
# 
# url: https://gmail.localhost:43199/gmail/1866867cfdb8b61e
# 
######################

Catch.onErrorInternalHandler @ webmail_bundle.js:70
Catch.reportErr @ webmail_bundle.js:103
GmailElementReplacer.handleException @ webmail_bundle.js:14274
GmailElementReplacer.replaceArmoredBlocks @ webmail_bundle.js:13829
Show 4 more frames
Show less
webmail_bundle.js:74 GoogleAuth is not defined
ReferenceError: GoogleAuth is not defined
    at Google.gmailCall (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:8911:48)
    at Gmail.msgGet (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:8482:37)
    at Downloader.msgGetFull (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:10989:46)
    at chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:11665:75
    at MessageRenderer.msgGetProcessed (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:11670:23)
    at GmailElementReplacer.replaceArmoredBlocks (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13826:79)
    at GmailElementReplacer.everything (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13801:18)
    at Object.handler (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:13735:55)
    at Object.start (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:15238:46)
    at async entrypoint (chrome-extension://kkkcphgncpnmjbjjhcibodcnihjmdlfi/js/content_scripts/webmail_bundle.js:15060:21)
    at <async> gmailCall (/extension/js/common/api/email-provider/gmail/google.ts:18:28)
    at <async> msgGet (/extension/js/common/api/email-provider/gmail/gmail.ts:110:18)
    at <async> msgGetFull (/extension/js/common/downloader.ts:53:22)
    at <async> <anonymous> (/extension/js/common/message-renderer.ts:391:20)
```
Any suggestion or feedback is highly appreciated. Thanks in advance.

### PR DESCRIPTION
**Pull request by martgil**
This PR adds a new Class named OAuth that Google-Auth inherited.

close https://github.com/FlowCrypt/flowcrypt-browser/issues/5316
close #5335

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by martgil** [comment]
@sosnovsky ready for review. thank you.

File: tooling/bundle-content-scripts.ts [hunk 1]
```diff
@@ -45,6 +45,7 @@ buildContentScript(
     getFilesInDir(`${sourceDir}/js/common/api/shared`, /\.js$/, false),
     getFilesInDir(`${sourceDir}/js/common/api/key-server`, /\.js$/, false),
     getFilesInDir(`${sourceDir}/js/common/api/account-servers`, /\.js$/, false),
+    getFilesInDir(`${sourceDir}/js/common/api/authentication`, /\.js$/, false, true),
```
Comment (sosnovsky) [inline tooling/bundle-content-scripts.ts:48]: it'll be better to create separate folder `/api/authentication/google` and store `google-oauth.ts` there (like we already do in `email-provider` folder), instead of adding `reverseFilesInDir` parameter.
as it's possible that we'll have another `..-oauth.ts` file which alphabetically will be after `oauth.ts` and `reverseFilesInDir` won't work in this case.

Comment (martgil) [reply tooling/bundle-content-scripts.ts:48]: Ok thanks. I think I get you the idea. Will do - thank you.

**Comment by martgil** [comment]
ready for review again. thank you 😅.

**Review by tomholub — APPROVED** [review]
