### PR TITLE
Configure sending options prior typing in ComposePageRecipe

### LINKED ISSUE #5052: Compose test unstable possibly due to sendingOpts
The test `compose - saving and rendering a draft with RTL text (rich text)` fails possibly because "Saved" (to drafts) indicator gets wiped away when the recipe selects "Rich Text" sending options, and then "Saved" never appears, causing the test to fail.

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
This PR first sets up sending options, then types the message, invoking draft save.

close #5052

---------------------------------

**Tests** _(delete all except exactly one)_:
- internal test refactoring

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Review by sosnovsky — COMMENTED** [review]
I tried to reproduce bug which you described in https://github.com/FlowCrypt/flowcrypt-browser/issues/5052, but it works well for me - `Saved` label appears even after clicking checkbox for `Rich text`. Were you able to reproduce it?

Also for this case I think we should fix extension behavior, not change test, as users should see `Saved` label even when they click sending options checkboxes after composing message.

**Comment by rrrooommmaaa** [comment]
> I tried to reproduce bug which you described in #5052, but it works well for me - `Saved` label appears even after clicking checkbox for `Rich text`. Were you able to reproduce it?

Yes, in Firefox, after typing something, when "Saved" appears, I switch "Rich Text" from "off" to "on" -- "Saved" gets immediately cleared and doesn't re-appear.
Important: If switching "Rich text" from "on" to "off", then "Saved" appears because this switch results in message re-formatting with draft save.

> Also for this case I think we should fix extension behavior, not change test, as users should see Saved label even when they click sending options checkboxes after composing message.

Maybe they should, but switching the options takes some time, and as "Saved" may appear before (or during) the switching,  there will be less time left to check that "Saved" is "continuously visible", potentially leading to unstable test.

**Review by sosnovsky — DISMISSED** [review]

**Comment by rrrooommmaaa** [comment]
How can I see the actual failed assertion?

**Comment by sosnovsky** [comment]
> How can I see the actual failed assertion?

https://flowcrypt.semaphoreci.com/workflows/c6f72f99-cc1e-4b59-b8f4-101d97f25a5e/summary?pipeline_id=e4cefd3d-9a70-4a52-b77c-7201a721cc00&report_id=4ae71336-e44b-39bf-b9d2-752e234818a5

Screenshot 2023-04-04 at 14 41 09

**Comment by sosnovsky** [comment]
And exact assertion is shown here, I think - https://storage.googleapis.com/p8ejr437e40a1hc10jpmsp5q2wfx83/artifacts/jobs/c309e55f-8e74-493c-9e53-38874c19f3c4/debugHtmlAttachment-0.html?Expires=1680609800&GoogleAccessId=artifacthub%40semaphore2-prod-artifacts.iam.gserviceaccount.com&Signature=b3Lzm%2BOOJCUbQGXGfYL2xnElyvbvY7qYKQ6lLolZAP4L%2FhKMqQ71x4q4EgxvXZtU%2BWDcfZmROjalQBj6knP1PCIPku%2FWBoCoYFyu5liTOKl9HDIZv9Mzxg79y6BakwHrLQ9t8m8vqcmayvhQCQ7jUs%2B8WeLqHMwD898DhyH3b5Ql9FSi0GADNOJ0k8rOEEWhd1H1BwxSJ1se2EWVPLH0Oxvcxh9I2QcnlxRB10vF0d9%2FDZ4GL%2Fc%2FMp7uWk7%2B1cLaiDw88AygcUZUpxKZI0FnhwlNV8TxaoIh%2FlzgxgqxHkXOmkr7PGzERU2VnCisxTSwoC8xuE2R4TtPZ95a0jKCGQ%3D%3D&response-content-disposition=inline&response-content-type=text/html;%20charset=utf-8

Screenshot 2023-04-04 at 14 43 44

**Comment by rrrooommmaaa** [comment]
We need to extract this meaningful piece into the test result:
```
  ✘ [fail]: compose - saving and rendering a draft with RTL text (plain text) [ALL RETRIES FAILED for compose - saving and rendering a draft with RTL text (plain text)]
    ℹ (attempt 1 of 1) Failed:   AssertionError: expected '<div><br></div><div><br></div><div>--…' to include '<div dir="rtl">مرحبا<br></div>'
          at <anonymous> (/home/osboxes/flowcrypt-browser/test/source/tests/compose.ts:1508:62)
          at <anonymous> (/home/osboxes/flowcrypt-browser/test/source/test.ts:81:11)
          at BrowserPool.BrowserPool.withNewBrowserTimeoutAndRetry (/home/osboxes/flowcrypt-browser/test/source/browser/browser-pool.ts:113:11)
          at <anonymous> (/home/osboxes/flowcrypt-browser/test/source/test.ts:75:7)
          at <async> <anonymous> (/test/source/tests/compose.ts:1495:39)
          at <async> <anonymous> (../test/source/test.ts:75:55)
```
The line with `(attempt x of x) Failed` (last attempt)

File: test/source/tests/compose.ts [hunk 1]
```diff
@@ -2661,8 +2661,10 @@ export const defineComposeTests = (testVariant: TestVariant, testWithBrowser: Te
         const settingsPage = await BrowserRecipe.openSettingsLoginApprove(t, browser, acct);
         await SetupPageRecipe.autoSetupWithEKM(settingsPage);
         const composePage = await ComposePageRecipe.openStandalone(t, browser, acct);
-        await ComposePageRecipe.fillMsg(composePage, { to: 'mock.only.pubkey@flowcrypt.com' }, 'no valid key');
-        await ComposePageRecipe.waitForToastToAppearAndDisappear(composePage, 'Draft not saved: Error: Your account keys are revoked');
+        await Promise.all([
+          ComposePageRecipe.fillMsg(composePage, { to: 'mock.only.pubkey@flowcrypt.com' }, 'no valid key'),
+          ComposePageRecipe.waitForToastToAppearAndDisappear(composePage, 'Draft not saved: Error: Your account keys are revoked'),
```
Comment (rrrooommmaaa) [inline test/source/tests/compose.ts:2666]: This toast appears only once, doesn't reappear on further edits, is this behavior expected?

Comment (sosnovsky) [reply test/source/tests/compose.ts:2666]: Yes, it's expected behavior - we set `disableSendingDrafts` to `true` in case of such error (as there is no reason to retry draft saving)

https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/chrome/elements/compose-modules/compose-draft-module.ts#L183

**Review by sosnovsky — APPROVED** [review]
Well done 👍
